const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
const venv = path.join(root, '.venv');
const python = process.platform === 'win32' ? path.join(venv, 'Scripts', 'python.exe') : path.join(venv, 'bin', 'python');
const run = (command, args) => { const result = spawnSync(command, args, { cwd: root, stdio: 'inherit' }); if (result.error) throw result.error; if ((result.status ?? 1) !== 0) throw new Error(`${command} failed with code ${result.status}`); };
if (process.platform !== 'win32') throw new Error('Team-retouch release runtime is Windows Python 3.12 x64 only.');
if (!fs.existsSync(python)) run('py', ['-3.12-64', '-m', 'venv', venv]);
run(python, ['-c', 'import platform,sys; assert sys.version_info[:2]==(3,12) and platform.architecture()[0]=="64bit", "Python 3.12 x64 is required"']);
const hashedLock = path.join(root, 'requirements-build.lock');
run(python, ['-m', 'pip', 'install', '--disable-pip-version-check', ...(fs.existsSync(hashedLock) ? ['--require-hashes','--no-deps','-r',hashedLock] : ['-r','requirements-build.txt'])]);
run(python, ['-c', 'import cv2, onnxruntime, PIL, numpy; print("Plugin Python 3.12 x64 environment ready")']);
