const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
const venv = path.join(root, '.venv');
const python = process.platform === 'win32' ? path.join(venv, 'Scripts', 'python.exe') : path.join(venv, 'bin', 'python');
const run = (command, args) => { const result = spawnSync(command, args, { cwd: root, stdio: 'inherit' }); if (result.error) throw result.error; if ((result.status ?? 1) !== 0) throw new Error(`${command} failed with code ${result.status}`); };
if (!fs.existsSync(python)) run(process.platform === 'win32' ? 'py' : 'python3', process.platform === 'win32' ? ['-3', '-m', 'venv', venv] : ['-m', 'venv', venv]);
run(python, ['-m', 'pip', 'install', '--disable-pip-version-check', '-r', 'requirements-build.txt']);
run(python, ['-c', 'import cv2, onnxruntime, PIL, numpy; print("Plugin Python environment ready")']);
