const { contextBridge, ipcRenderer } = require('electron');

const RENDERER_PYTHON_TOOLS = new Set(['catch.py', 'classify.py', 'cut_video.py', 'ffmpeg_transcode.py', 'png_to_jpg.py', 'research.py']);
const validatePythonInvocation = (scriptName, args, requestId) => {
  if (typeof scriptName !== 'string' || !RENDERER_PYTHON_TOOLS.has(scriptName)) throw new Error('Python tool is not available');
  if (!Array.isArray(args) || args.length > 256 || args.some(value => typeof value !== 'string' || value.length > 32768 || /[\0\r\n]/.test(value))) {
    throw new TypeError('Invalid Python tool arguments');
  }
  const normalizedRequestId = String(requestId || '');
  if (normalizedRequestId && !/^[a-z0-9-]{8,80}$/i.test(normalizedRequestId)) throw new Error('Invalid Python request identifier');
  return { scriptName, args, requestId: normalizedRequestId };
};

const trackFeature = feature => ipcRenderer.send('telemetry-track', 'feature_used', { feature });
const invokeFeature = (feature, channel, ...args) => {
  trackFeature(feature);
  return ipcRenderer.invoke(channel, ...args);
};

contextBridge.exposeInMainWorld('electronAPI', {
  apiContractVersion: 1,
  runScript: (scriptName, args, requestId) => {
    const invocation = validatePythonInvocation(scriptName, args, requestId);
    const feature = invocation.scriptName.replace(/\.py$/i, '').slice(0, 48);
    if (feature) trackFeature(feature);
    ipcRenderer.send('run-python', invocation.scriptName, invocation.args, invocation.requestId);
  },
  cancelPythonTask: (requestId) => ipcRenderer.invoke('cancel-python', requestId),
  getBirthdays: () => ipcRenderer.invoke('get-birthdays'),
  saveBirthdays: (data) => ipcRenderer.invoke('save-birthdays', data),
  onPythonEvent: (callback) => {
    const subscription = (_event, value) => callback(value);
    ipcRenderer.on('python-event', subscription);
    return () => ipcRenderer.removeListener('python-event', subscription);
  },
  loadConfig: () => ipcRenderer.invoke('loadConfig'),
  saveConfig: (config) => ipcRenderer.invoke('saveConfig', config),
  getPrivacyConsentState: () => ipcRenderer.invoke('privacy-consent-state'),
  savePrivacyConsent: (request) => ipcRenderer.invoke('privacy-consent-save', request),
  openLegalDocument: (documentId) => ipcRenderer.invoke('privacy-open-legal-document', documentId),
  clearTelemetryLocalData: () => ipcRenderer.invoke('privacy-clear-telemetry-local-data'),
  getUserPath: () => ipcRenderer.invoke('getUserPath'),
  onUpdateAvailable: (callback) => {
    const subscription = (_event, value) => callback(value);
    ipcRenderer.on('update-available', subscription);
    return () => ipcRenderer.removeListener('update-available', subscription);
  },
  openExternal: (url) => ipcRenderer.send('open-external', url),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  submitFeedback: (message) => ipcRenderer.invoke('submit-feedback', message),
  getComponents: () => ipcRenderer.invoke('components-list'),
  onComponentsStatusChanged: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('components-status-changed', subscription); return () => ipcRenderer.removeListener('components-status-changed', subscription); },
  openComponentsFolder: (componentId) => ipcRenderer.invoke('components-open-folder', componentId),
  openLogsFolder: () => ipcRenderer.invoke('logs-open-folder'),
  clearLogs: () => ipcRenderer.invoke('logs-clear'),
  clearInterfaceCache: () => ipcRenderer.invoke('interface-cache-clear'),
  getCursorScreenPoint: () => ipcRenderer.invoke('cursor-screen-point'),
  installComponent: (componentId) => ipcRenderer.invoke('components-install', componentId),
  deleteComponentPackage: (kind, componentId) => ipcRenderer.invoke('components-delete-package', kind, componentId),
  uninstallComponent: (componentId) => ipcRenderer.invoke('components-uninstall', componentId),
  checkTeamRetouchAdvancedRequirements: () => ipcRenderer.invoke('team-retouch-advanced-preflight'),
  installTeamRetouchAdvanced: (options) => ipcRenderer.invoke('team-retouch-advanced-install', options),
  uninstallTeamRetouchAdvanced: () => ipcRenderer.invoke('team-retouch-advanced-uninstall'),
  onTeamRetouchAdvancedProgress: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('team-retouch-advanced-progress', subscription); return () => ipcRenderer.removeListener('team-retouch-advanced-progress', subscription); },
  getDrives: () => ipcRenderer.invoke('getDrives'),
  getWorkspaceProjects: (workspacePath) => ipcRenderer.invoke('workspace-projects', workspacePath),
  onWorkspaceFilesChanged: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-files-changed', subscription); return () => ipcRenderer.removeListener('workspace-files-changed', subscription); },
  onWorkspaceProjectsChanged: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-projects-changed', subscription); return () => ipcRenderer.removeListener('workspace-projects-changed', subscription); },
  createWorkspaceProject: (workspacePath, date, name, options) => ipcRenderer.invoke('workspace-create-project', workspacePath, date, name, options),
  renameWorkspaceProject: (workspacePath, status, name, date, nextName) => ipcRenderer.invoke('workspace-rename-project', workspacePath, status, name, date, nextName),
  renameProjectFolder: (workspacePath, status, name, folderName, nextName) => ipcRenderer.invoke('workspace-rename-project-folder', workspacePath, status, name, folderName, nextName),
  createProjectFolder: (workspacePath, status, name, folderName, relativePath, makeUnique) => ipcRenderer.invoke('workspace-create-project-folder', workspacePath, status, name, folderName, relativePath, makeUnique),
  getShellNewFileTypes: (refresh = false) => ipcRenderer.invoke('workspace-shell-new-types', refresh),
  createProjectShellNewFile: (workspacePath, status, name, relativePath, typeId) => ipcRenderer.invoke('workspace-create-shell-new-file', workspacePath, status, name, relativePath, typeId),
  undoLastRename: (workspacePath, options) => ipcRenderer.invoke('workspace-undo-rename', workspacePath, options),
  moveWorkspaceProject: (workspacePath, status, name, nextStatus) => ipcRenderer.invoke('workspace-move-project', workspacePath, status, name, nextStatus),
  archiveImportedProjects: (workspacePath, projectNames) => ipcRenderer.invoke('workspace-archive-imports', workspacePath, projectNames),
  trashWorkspaceProject: (workspacePath, status, name) => ipcRenderer.invoke('workspace-trash-project', workspacePath, status, name),
  cleanupDeletedWorkspaceProjects: (workspacePath) => ipcRenderer.invoke('workspace-cleanup-deleted-projects', workspacePath),
  getProjectContents: (workspacePath, status, name) => ipcRenderer.invoke('workspace-project-contents', workspacePath, status, name),
  watchFileRoot: (workspacePath, status, name) => ipcRenderer.invoke('workspace-watch-file-root', workspacePath, status, name),
  unwatchFileRoot: (workspacePath, status, name) => ipcRenderer.invoke('workspace-unwatch-file-root', workspacePath, status, name),
  browseProjectFiles: (workspacePath, status, name, relativePath, cacheConfig) => ipcRenderer.invoke('workspace-browse-files', workspacePath, status, name, relativePath, cacheConfig),
  inspectProjectToolSources: (workspacePath, status, name, relativePaths, collectVideos, collectDirectPng) => ipcRenderer.invoke('workspace-inspect-tool-sources', workspacePath, status, name, relativePaths, collectVideos, collectDirectPng),
  resolveProjectShortcut: (workspacePath, status, name, relativePath) => ipcRenderer.invoke('workspace-resolve-shortcut', workspacePath, status, name, relativePath),
  searchProjectFiles: (workspacePath, status, name, scopeRelativePath, query) => ipcRenderer.invoke('workspace-search-files', workspacePath, status, name, scopeRelativePath, query),
  listRecentProjectFiles: (workspacePath, status, name, scopeRelativePath, limit, cursor) => ipcRenderer.invoke('workspace-recent-files', workspacePath, status, name, scopeRelativePath, limit, cursor),
  listWorkspaceFolders: (workspacePath, status, name) => ipcRenderer.invoke('workspace-folder-tree', workspacePath, status, name),
  addInspirationToProject: (inspirationRoot, targetWorkspacePath, targetStatus, targetProjectName, relativePaths) => ipcRenderer.invoke('workspace-add-inspiration-to-project', inspirationRoot, targetWorkspacePath, targetStatus, targetProjectName, relativePaths),
  extractOfficeImages: (workspacePath, status, name, relativePaths) => invokeFeature('office_media_extract', 'workspace-extract-office-images', workspacePath, status, name, relativePaths),
  extractScreenshotMainImages: (workspacePath, status, name, relativePaths, options) => invokeFeature('screenshot_main_image', 'workspace-extract-screenshot-main-images', workspacePath, status, name, relativePaths, options),
  trimProjectVideo: (workspacePath, status, name, relativePath, request) => invokeFeature('video_trim', 'workspace-trim-video', workspacePath, status, name, relativePath, request),
  onScreenshotMainImageProgress: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-screenshot-main-image-progress', subscription); return () => ipcRenderer.removeListener('workspace-screenshot-main-image-progress', subscription); },
  getProjectFileDetails: (workspacePath, status, name, relativePaths) => ipcRenderer.invoke('workspace-file-details', workspacePath, status, name, relativePaths),
  getProjectEntryDetails: (workspacePath, status, name, relativePath) => ipcRenderer.invoke('workspace-entry-details', workspacePath, status, name, relativePath),
  getMediaVersions: (workspacePath, status, name, relativePath) => ipcRenderer.invoke('workspace-media-versions', workspacePath, status, name, relativePath),
  updateMediaVersion: (workspacePath, request) => ipcRenderer.invoke('workspace-version-update', workspacePath, request),
  relocateMediaVersion: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-version-relocate', workspacePath, status, projectName, request),
  deleteMediaVersion: (workspacePath, request) => ipcRenderer.invoke('workspace-version-delete', workspacePath, request),
  getMediaVersionDeleteScope: (workspacePath, versionId) => ipcRenderer.invoke('workspace-version-delete-scope', workspacePath, versionId),
  deleteProjectMissingMediaVersion: (workspacePath, versionId) => ipcRenderer.invoke('workspace-version-delete-project-missing', workspacePath, versionId),
  recordMediaVersionCompare: (workspacePath, request) => ipcRenderer.invoke('workspace-version-compare-record', workspacePath, request),
  openMediaVersion: (filePath) => ipcRenderer.invoke('workspace-open-version', filePath),
  getProgressFolders: (workspacePath, projectName) => ipcRenderer.invoke('workspace-progress-folders', workspacePath, projectName),
  ensureSelectionBaseline: (workspacePath, status, projectName) => ipcRenderer.invoke('workspace-selection-baseline-ensure', workspacePath, status, projectName),
  getFinalVersionSummary: (workspacePath, projectName) => ipcRenderer.invoke('workspace-final-version-summary', workspacePath, projectName),
  browseFinalVersions: (workspacePath, status, projectName) => ipcRenderer.invoke('workspace-final-version-browse', workspacePath, status, projectName),
  exportFinalVersions: (workspacePath, status, projectName) => invokeFeature('final_version_export', 'workspace-final-version-export', workspacePath, status, projectName),
  createProgressFolder: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-create-progress-folder', workspacePath, status, projectName, request),
  registerProgressFolder: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-progress-register', workspacePath, status, projectName, request),
  updateProgressFolder: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-progress-update', workspacePath, status, projectName, request),
  deleteMissingProgressFolder: (workspacePath, projectName, progressId) => ipcRenderer.invoke('workspace-progress-delete-missing', workspacePath, projectName, progressId),
  registerVersionBaseline: (workspacePath, status, projectName, relativePath) => ipcRenderer.invoke('workspace-version-register-baseline', workspacePath, status, projectName, relativePath),
  compareVersionFolders: (workspacePath, status, projectName, referenceRelativePath, sourceRelativePath, sourceNames) => invokeFeature('version_folder_compare', 'workspace-version-compare-preview', workspacePath, status, projectName, referenceRelativePath, sourceRelativePath, sourceNames),
  commitVersionBatch: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-version-batch-commit', workspacePath, status, projectName, request),
  getVersionBatchOperations: (workspacePath, batchId) => ipcRenderer.invoke('workspace-version-batch-operations', workspacePath, batchId),
  retryVersionBatchOperations: (workspacePath, batchId) => ipcRenderer.invoke('workspace-version-batch-retry', workspacePath, batchId),
  getTeamPatches: (workspacePath, status, projectName, relativePath) => ipcRenderer.invoke('workspace-team-patches', workspacePath, status, projectName, relativePath),
  getTeamProjectWorkspace: (workspacePath, projectName, status) => ipcRenderer.invoke('workspace-team-project', workspacePath, projectName, status),
  getTeamIdentitySimilarities: (workspacePath, projectName) => ipcRenderer.invoke('workspace-team-identity-similarities', workspacePath, projectName),
  registerTeamProjectPhotos: (workspacePath, status, projectName, relativePaths) => ipcRenderer.invoke('workspace-team-project-register', workspacePath, status, projectName, relativePaths),
  suggestTeamIdentities: (workspacePath, projectName) => ipcRenderer.invoke('workspace-team-identities-suggest', workspacePath, projectName),
  saveTeamIdentity: (workspacePath, request) => ipcRenderer.invoke('workspace-team-identity-save', workspacePath, request),
  assignTeamIdentity: (workspacePath, request) => ipcRenderer.invoke('workspace-team-identity-assign', workspacePath, request),
  confirmTeamIdentityGroup: (workspacePath, request) => ipcRenderer.invoke('workspace-team-identity-confirm-group', workspacePath, request),
  completeTeamIdentity: (workspacePath, request) => ipcRenderer.invoke('workspace-team-identity-complete', workspacePath, request),
  deleteTeamIdentity: (workspacePath, request) => ipcRenderer.invoke('workspace-team-identity-delete', workspacePath, request),
  saveTeamWorkflowSettings: (workspacePath, request) => ipcRenderer.invoke('workspace-team-workflow-settings-save', workspacePath, request),
  excludeTeamPerson: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-team-person-exclude', workspacePath, status, projectName, request),
  removeProjectTeamPhoto: (workspacePath, request) => ipcRenderer.invoke('workspace-team-project-remove-photo', workspacePath, request),
  generateTeamWorkflow: (workspacePath, status, projectName, request) => invokeFeature('team_workflow_generate', 'workspace-team-workflow-generate', workspacePath, status, projectName, request),
  getTeamWorkflowGenerationStatus: (workspacePath, status, projectName) => ipcRenderer.invoke('workspace-team-workflow-status', workspacePath, status, projectName),
  cancelTeamWorkflowGeneration: (operationId) => ipcRenderer.invoke('workspace-team-workflow-cancel', operationId),
  onTeamWorkflowGenerationProgress: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-team-workflow-progress', subscription); return () => ipcRenderer.removeListener('workspace-team-workflow-progress', subscription); },
  exportTeamIdentityTasks: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-team-identity-export', workspacePath, status, projectName, request),
  returnTeamWorkflowBatch: (workspacePath, projectName, request) => ipcRenderer.invoke('workspace-team-workflow-return-batch', workspacePath, projectName, request),
  getTeamWorkflowReturnReview: (workspacePath, projectName, status) => ipcRenderer.invoke('workspace-team-workflow-return-review-get', workspacePath, projectName, status),
  discardTeamWorkflowReturnReview: (workspacePath, projectName, reviewSessionId) => ipcRenderer.invoke('workspace-team-workflow-return-review-discard', workspacePath, projectName, reviewSessionId),
  detectTeamPatchPeople: (workspacePath, status, projectName, request) => invokeFeature('team_person_detect', 'workspace-team-patch-detect', workspacePath, status, projectName, request),
  onTeamPatchDetectionProgress: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-team-patch-detect-progress', subscription); return () => ipcRenderer.removeListener('workspace-team-patch-detect-progress', subscription); },
  detectTeamPatchBatch: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-team-patch-detect-batch', workspacePath, status, projectName, request),
  onTeamPatchBatchProgress: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-team-patch-detect-batch-progress', subscription); return () => ipcRenderer.removeListener('workspace-team-patch-detect-batch-progress', subscription); },
  updateTeamPatch: (workspacePath, request) => ipcRenderer.invoke('workspace-team-patch-update', workspacePath, request),
  deleteTeamPatch: (workspacePath, request) => ipcRenderer.invoke('workspace-team-patch-delete', workspacePath, request),
  cleanupTeamPatches: (workspacePath, request) => ipcRenderer.invoke('workspace-team-patch-cleanup', workspacePath, request),
  uploadTeamPatch: (workspacePath, request) => ipcRenderer.invoke('workspace-team-patch-upload', workspacePath, request),
  removeTeamPatchUpload: (workspacePath, request) => ipcRenderer.invoke('workspace-team-patch-remove-upload', workspacePath, request),
  selectTeamPatchReturns: (projectName) => ipcRenderer.invoke('workspace-team-patch-select-returns', projectName),
  returnTeamPatchBatch: (workspacePath, status, projectName, request) => ipcRenderer.invoke('workspace-team-patch-return-batch', workspacePath, status, projectName, request),
  confirmTeamWorkflowReturn: (workspacePath, projectName, request) => ipcRenderer.invoke('workspace-team-workflow-return-confirm', workspacePath, projectName, request),
  onTeamPatchReturnBatchProgress: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-team-patch-return-batch-progress', subscription); return () => ipcRenderer.removeListener('workspace-team-patch-return-batch-progress', subscription); },
  openTeamPatch: (filePath) => ipcRenderer.invoke('workspace-team-patch-open', filePath),
  openTeamPatchFolder: (filePath) => ipcRenderer.invoke('workspace-team-patch-open-folder', filePath),
  mergeTeamPatches: (workspacePath, status, projectName, request) => invokeFeature('team_patch_merge', 'workspace-team-patch-merge', workspacePath, status, projectName, request),
  getMediaThumbnail: (filePath, kind, cacheConfig, requestedSize, priority, queueOrder) => ipcRenderer.invoke('media-thumbnail', filePath, kind, cacheConfig, requestedSize, priority, queueOrder),
  cancelMediaThumbnail: (filePath, requestedSize) => ipcRenderer.invoke('media-thumbnail-cancel', filePath, requestedSize),
  onThumbnailStateChanged: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('thumbnail-state-changed', subscription); return () => ipcRenderer.removeListener('thumbnail-state-changed', subscription); },
  startAdvancedVideo: (filePath, arrowKeyAction) => ipcRenderer.invoke('advanced-video-start', filePath, arrowKeyAction),
  setAdvancedVideoBounds: (sessionId, bounds) => ipcRenderer.send('advanced-video-bounds', sessionId, bounds),
  controlAdvancedVideo: (sessionId, request) => ipcRenderer.send('advanced-video-control', sessionId, request),
  captureAdvancedVideoFrame: (sessionId) => ipcRenderer.invoke('advanced-video-screenshot', sessionId),
  stopAdvancedVideo: (sessionId) => ipcRenderer.invoke('advanced-video-stop', sessionId),
  onAdvancedVideoState: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('advanced-video-state', subscription); return () => ipcRenderer.removeListener('advanced-video-state', subscription); },
  getMediaOriginal: (filePath, kind, cacheConfig) => ipcRenderer.invoke('media-original', filePath, kind, cacheConfig),
  getMediaMetadata: (filePath) => ipcRenderer.invoke('media-metadata', filePath),
  reportRendererError: (message, details) => ipcRenderer.send('renderer-error-log', message, details),
  trackTelemetry: (eventName, properties) => ipcRenderer.send('telemetry-track', eventName, properties),
  onAppError: (callback) => { const subscription = (_event, message) => callback(message); ipcRenderer.on('app-error', subscription); return () => ipcRenderer.removeListener('app-error', subscription); },
  getRawPreview: (filePath, cacheConfig) => ipcRenderer.invoke('media-raw-preview', filePath, cacheConfig),
  projectFileOperation: (workspacePath, status, projectName, operation, paths, targetRelativePath, nextName, options) => ipcRenderer.invoke('workspace-file-operation', workspacePath, status, projectName, operation, paths, targetRelativePath, nextName, options),
  getProjectFileClipboardStatus: () => ipcRenderer.invoke('workspace-file-clipboard-status'),
  cancelProjectFileCut: (workspacePath, status, projectName, paths) => ipcRenderer.invoke('workspace-cancel-file-cut', workspacePath, status, projectName, paths),
  startProjectFileDrag: (workspacePath, status, projectName, paths) => ipcRenderer.send('workspace-start-file-drag', workspacePath, status, projectName, paths),
  onProjectFileDragEnd: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-file-drag-ended', subscription); return () => ipcRenderer.removeListener('workspace-file-drag-ended', subscription); },
  onProjectFileOperationProgress: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('workspace-file-operation-progress', subscription); return () => ipcRenderer.removeListener('workspace-file-operation-progress', subscription); },
  cancelProjectFileOperation: (operationId) => ipcRenderer.invoke('workspace-cancel-file-operation', operationId),
  chooseCacheDirectory: () => ipcRenderer.invoke('choose-cache-directory'),
  chooseWorkspaceDirectory: (currentPath) => ipcRenderer.invoke('choose-workspace-directory', currentPath),
  chooseImportSourceFiles: () => ipcRenderer.invoke('choose-import-source-files'),
  chooseVideoFiles: () => ipcRenderer.invoke('choose-video-files'),
  getMediaCacheInfo: (cacheConfig) => ipcRenderer.invoke('media-cache-info', cacheConfig),
  clearMediaCache: (cacheConfig, olderThanDays) => ipcRenderer.invoke('media-cache-clear', cacheConfig, olderThanDays),
  getStorageUsageOverview: (force) => ipcRenderer.invoke('storage-usage-overview', force),
  getBackgroundTasks: () => ipcRenderer.invoke('background-tasks-list'),
  cancelBackgroundTask: (id) => ipcRenderer.invoke('background-task-cancel', id),
  dismissBackgroundTask: (id) => ipcRenderer.invoke('background-task-dismiss', id),
  retryBackgroundTask: (id) => ipcRenderer.invoke('background-task-retry', id),
  onBackgroundTaskChanged: (callback) => { const subscription = (_event, value) => callback(value); ipcRenderer.on('background-task-changed', subscription); return () => ipcRenderer.removeListener('background-task-changed', subscription); },
  chooseBackupTarget: (currentPath) => ipcRenderer.invoke('backup-choose-target', currentPath),
  getBackupStatus: (workspacePath) => ipcRenderer.invoke('backup-status', workspacePath),
  setNasBackupTarget: (targetPath) => ipcRenderer.invoke('backup-set-nas-target', targetPath),
  saveNasCredential: (request) => ipcRenderer.invoke('backup-save-nas-credential', request),
  readNasCredential: (credentialRef) => ipcRenderer.invoke('backup-read-nas-credential', credentialRef),
  deleteNasCredential: (credentialRef) => ipcRenderer.invoke('backup-delete-nas-credential', credentialRef),
  testBackupConnection: () => ipcRenderer.invoke('backup-test-connection'),
  getBackupSpaceStatus: (workspacePath) => ipcRenderer.invoke('backup-space-status', workspacePath),
  cleanupBackup: (workspacePath) => ipcRenderer.invoke('backup-cleanup', workspacePath),
  runBackup: (workspacePath, reason) => ipcRenderer.invoke('backup-run', workspacePath, reason),
  runBackupIfDue: (workspacePath) => ipcRenderer.invoke('backup-run-if-due', workspacePath),
  verifyBackup: (workspacePath, snapshotId) => ipcRenderer.invoke('backup-verify', workspacePath, snapshotId),
  restoreBackupWorkspace: (workspacePath, snapshotId) => ipcRenderer.invoke('backup-restore-workspace', workspacePath, snapshotId),
  restoreBackupProject: (workspacePath, snapshotId, projectId) => ipcRenderer.invoke('backup-restore-project', workspacePath, snapshotId, projectId),
  openBackupTarget: () => ipcRenderer.invoke('backup-open-target'),
  chooseArchiveTarget: (currentPath) => ipcRenderer.invoke('archive-choose-target', currentPath),
  getArchiveStatus: () => ipcRenderer.invoke('archive-status'),
  archiveWorkspaceProject: (workspacePath, projectName) => ipcRenderer.invoke('archive-project', workspacePath, projectName),
  moveArchivedProjectBack: (workspacePath, projectName, statusAfter) => ipcRenderer.invoke('archive-move-back', workspacePath, projectName, statusAfter),
  openArchiveTarget: () => ipcRenderer.invoke('archive-open-target'),
  openWorkspaceProject: (workspacePath, status, name, folderName) => ipcRenderer.invoke('workspace-open-project', workspacePath, status, name, folderName),
  openProjectEntry: (workspacePath, status, name, relativePath) => ipcRenderer.invoke('workspace-open-entry', workspacePath, status, name, relativePath),
  getPhotoshopStatus: () => ipcRenderer.invoke('photoshop-status'),
  openProjectEntriesInPhotoshop: (workspacePath, status, name, relativePaths) => invokeFeature('photoshop_open', 'workspace-open-entry-photoshop', workspacePath, status, name, relativePaths),
  copyProjectEntryPath: (workspacePath, status, name, relativePath) => ipcRenderer.invoke('workspace-copy-entry-path', workspacePath, status, name, relativePath),
  getFileIcon: (filePath) => ipcRenderer.invoke('workspace-entry-file-icon', filePath),
  importProjectFiles: (workspacePath, status, name, relativePath, options) => ipcRenderer.invoke('workspace-import-files', workspacePath, status, name, relativePath, options),
  importProgressFiles: (workspacePath, status, name, folderName, options) => ipcRenderer.invoke('workspace-import-progress-files', workspacePath, status, name, folderName, options),
  importBroll: (workspacePath, status, name, options) => ipcRenderer.invoke('workspace-import-broll', workspacePath, status, name, options),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  minimizeWindow: () => ipcRenderer.send('window-minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window-toggle-maximize'),
  closeWindow: () => ipcRenderer.send('window-close'),
  isWindowMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  setWindowFullscreen: (enabled) => ipcRenderer.invoke('window-set-fullscreen', enabled),
  onWindowMaximizedChange: (callback) => { const subscription = (_event, maximized) => callback(maximized); ipcRenderer.on('window-maximized-change', subscription); return () => ipcRenderer.removeListener('window-maximized-change', subscription); },
});
