import { useEffect, useMemo, useRef, useState } from 'react';
import { useHostSurfaceSuspension } from '../../components/LayerProvider';
import { ComponentIcon } from '../../components/ComponentIcon';
import type { ComponentContribution, ComponentPageOpenScope, WorkspaceProject } from '../../types';
import { clampCommandIndex, nextCommandIndex, shouldRegisterCommandShortcut } from './component-command-palette-model';
import { ComponentToolPanelSurface } from './ComponentToolPanelSurface';

type Opened = { contribution: ComponentContribution; instanceId: string; contentHeight?: number };
export const ComponentContributionDock = ({ contributions, project, workspacePath = '', scope = { scopeRelativePath: '', selectedRelativePaths: [], sourcePageId: '' }, active = true }: { contributions: ComponentContribution[]; project?: WorkspaceProject; workspacePath?: string; scope?: ComponentPageOpenScope; active?: boolean }) => {
  const [opened, setOpened] = useState<Opened | null>(null); const [commandsOpen, setCommandsOpen] = useState(false); const [query, setQuery] = useState(''); const [activeCommandIndex, setActiveCommandIndex] = useState(-1); const panelRef = useRef<HTMLDivElement>(null); const focusBeforeCommand = useRef<HTMLElement | null>(null); const [width, setWidth] = useState(360);
  useHostSurfaceSuspension(commandsOpen);
  const projectEntries = project ? contributions.filter(item => ['component.sidePanel', 'project.contextAction', 'project.exportProvider'].includes(item.type) && !item.placement) : []; const commands = contributions.filter(item => item.type === 'application.command'); const filtered = useMemo(() => commands.filter(item => item.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [commands, query]); const resolvedCommandIndex = clampCommandIndex(activeCommandIndex, filtered.length);
  const open = async (contribution: ComponentContribution, triggerScope = scope) => { const application = contribution.type === 'application.command'; if (!application && !project) return; const result = await window.electronAPI.openComponentContribution({ componentId: contribution.componentId, contributionId: contribution.contributionId, type: contribution.type, ...(application ? {} : { workspacePath, projectId: project!.id, projectName: project!.name, projectStatus: project!.status, ...triggerScope }) }); if (result.success && result.page) { setOpened({ contribution, instanceId: result.page.instanceId, contentHeight: result.page.contentHeight }); closeCommands(); } };
  const showCommands = () => { focusBeforeCommand.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setQuery(''); setActiveCommandIndex(0); setCommandsOpen(true); };
  const closeCommands = () => { setCommandsOpen(false); window.requestAnimationFrame(() => focusBeforeCommand.current?.focus()); };
  useEffect(() => { if (!shouldRegisterCommandShortcut(commands.length)) return; const listener = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLocaleLowerCase() === 'p') { event.preventDefault(); if (commandsOpen) closeCommands(); else showCommands(); } else if (event.key === 'Escape' && commandsOpen) closeCommands(); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); });
  useEffect(() => { if (!commands.length) setCommandsOpen(false); }, [commands.length]);
  useEffect(() => { setActiveCommandIndex(current => clampCommandIndex(current, filtered.length)); }, [filtered.length]);
  useEffect(() => { const listener = (event: Event) => { const detail = (event as CustomEvent<{ contribution: ComponentContribution; scope?: ComponentPageOpenScope }>).detail; if (active && detail?.contribution && (!detail.scope?.sourcePageId || detail.scope.sourcePageId === scope.sourcePageId)) void open(detail.contribution, detail.scope || scope); }; window.addEventListener('photoflow:open-component-contribution', listener); return () => window.removeEventListener('photoflow:open-component-contribution', listener); });
  useEffect(() => window.electronAPI.onComponentPanelCloseRequested(instanceId => { if (opened?.contribution.type === 'component.sidePanel' && opened.instanceId === instanceId) { void window.electronAPI.closeComponentPage(instanceId); setOpened(null); } }), [opened]);
  useEffect(() => { if (!opened?.instanceId || opened.contribution.type === 'component.sidePanel') return; const element = panelRef.current; if (!element) return; const update = () => { const bounds = element.getBoundingClientRect(); void window.electronAPI.setComponentPageBounds(opened.instanceId, { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height }); }; const observer = new ResizeObserver(update); observer.observe(element); void window.electronAPI.activateComponentPage(opened.instanceId); update(); return () => observer.disconnect(); }, [opened, width]);
  useEffect(() => { if (!active && opened) { void window.electronAPI.setComponentPageBounds(opened.instanceId, { x: 0, y: 0, width: 0, height: 0 }); void window.electronAPI.activateComponentPage(''); void window.electronAPI.closeComponentPage(opened.instanceId); setOpened(null); } }, [active, opened]);
  useEffect(() => () => { if (opened?.instanceId) void window.electronAPI.closeComponentPage(opened.instanceId); }, [opened]);
  useEffect(() => { if (opened && !contributions.some(item => item.componentId === opened.contribution.componentId && item.componentVersion === opened.contribution.componentVersion && item.contributionId === opened.contribution.contributionId)) { void window.electronAPI.closeComponentPage(opened.instanceId); setOpened(null); } }, [contributions, opened]);
  if (!projectEntries.length && !commands.length && !opened) return null;
  return <><div className="flex items-center gap-1" aria-label="插件入口">{projectEntries.map(item => <button key={`${item.componentId}:${item.contributionId}`} type="button" className="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-slate-600 hover:bg-slate-50" title={`${item.type} · ${item.title}`} onClick={() => void open(item)}><ComponentIcon src={item.iconUrl} size={14}/>{item.type === 'project.exportProvider' ? '导出：' : item.type === 'component.sidePanel' ? '面板：' : ''}{item.label}</button>)}{commands.length > 0 && <button type="button" aria-haspopup="dialog" className="rounded-md border border-slate-200 bg-white px-2 py-1 text-xs font-semibold text-slate-600" onClick={showCommands}>命令…</button>}</div>
    {opened?.contribution.type === 'component.sidePanel' && <ComponentToolPanelSurface
      contribution={opened.contribution}
      instanceId={opened.instanceId}
      initialContentHeight={opened.contentHeight}
      open
      onClose={() => { void window.electronAPI.closeComponentPage(opened.instanceId); setOpened(null); }}
    />}
    {opened && opened.contribution.type !== 'component.sidePanel' && <aside aria-label={opened.contribution.title} style={{ width }} className="fixed bottom-3 right-3 top-14 z-[210] rounded-xl border border-slate-200 bg-white shadow-2xl"><header className="absolute inset-x-0 top-0 z-10 flex h-10 items-center justify-end border-b border-slate-200 bg-white px-2"><button type="button" aria-label="关闭插件面板" onClick={() => { void window.electronAPI.closeComponentPage(opened.instanceId); setOpened(null); }} className="rounded px-2 py-1 text-xs">关闭</button></header><div ref={panelRef} data-component-view-host className="absolute inset-x-0 bottom-10 top-10"/><footer className="absolute inset-x-0 bottom-0 z-10 flex h-10 items-center border-t border-slate-200 bg-white px-3"><input aria-label="调整插件面板宽度" type="range" min="280" max="640" value={width} onChange={event => setWidth(Number(event.target.value))} className="w-28"/></footer></aside>}
    {commandsOpen && <div role="dialog" aria-modal="true" aria-label="插件命令" className="fixed inset-0 z-[430] flex items-start justify-center bg-slate-950/35 pt-[12vh]" onMouseDown={closeCommands}><div className="w-full max-w-xl rounded-xl bg-white p-3 shadow-2xl" onMouseDown={event => event.stopPropagation()}><input autoFocus aria-label="搜索插件命令" aria-controls="component-command-options" aria-activedescendant={resolvedCommandIndex >= 0 ? `component-command-${resolvedCommandIndex}` : undefined} value={query} onChange={event => { setQuery(event.target.value); setActiveCommandIndex(0); }} onKeyDown={event => { if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); setActiveCommandIndex(current => nextCommandIndex(current, filtered.length, event.key)); } else if (event.key === 'Enter' && filtered[resolvedCommandIndex]) { event.preventDefault(); void open(filtered[resolvedCommandIndex]); } else if (event.key === 'Escape') { event.preventDefault(); closeCommands(); } }} placeholder="搜索命令…" className="w-full rounded-lg border border-slate-300 px-3 py-2"/><div id="component-command-options" role="listbox" className="mt-2 max-h-80 overflow-auto">{filtered.map((item, index) => <button id={`component-command-${index}`} role="option" aria-selected={index === resolvedCommandIndex} key={`${item.componentId}:${item.contributionId}`} className={`block w-full rounded-lg px-3 py-2 text-left hover:bg-blue-50 focus:bg-blue-50 ${index === resolvedCommandIndex ? 'bg-blue-50' : ''}`} onMouseEnter={() => setActiveCommandIndex(index)} onClick={() => void open(item)}>{item.label}</button>)}{!filtered.length && <p className="p-3 text-sm text-slate-400">没有匹配命令</p>}</div><button type="button" className="mt-2 rounded px-3 py-1 text-sm" onClick={closeCommands}>关闭</button></div></div>}</>;
};
