const fs=require('node:fs');
const path=require('node:path');
const {spawn}=require('node:child_process');
const {privateOutputPath}=require('../../../scripts/project-output-paths.cjs');
const repository=path.resolve(__dirname,'../../..');
const output=privateOutputPath(repository,'diagnostics','visual-canvas-prototype',`run-${new Date().toISOString().replace(/[:.]/g,'-')}.log`);
fs.mkdirSync(path.dirname(output),{recursive:true});const log=fs.createWriteStream(output,{flags:'wx'});
const child=spawn(process.execPath,['--test','--test-reporter=spec','tests/core.test.cjs'],{cwd:path.resolve(__dirname,'..'),stdio:['ignore','pipe','pipe'],windowsHide:true});
child.stdout.on('data',bytes=>{process.stdout.write(bytes);log.write(bytes);});child.stderr.on('data',bytes=>{process.stderr.write(bytes);log.write(bytes);});
child.on('error',e=>{console.error(e);log.end(String(e));process.exitCode=1;});child.on('exit',code=>{log.end();console.log('Private test log: '+output);process.exitCode=code??1;});
