(() => {
  'use strict';
  const api = window.photoFlowComponent;
  const mode = document.documentElement.dataset.mode;
  const root = document.querySelector('#app');
  const defaults = { container:'mp4', videoMode:'h264', quality:'balanced', resolution:'original', frameRate:'original', audioMode:'aac', subtitleMode:'copy', colorMode:'auto', bitDepth:'auto', frameRateMode:'preserve', rotation:'auto', aspectMode:'preserve', audioTrack:'all', videoBitrateMbps:null, audioBitrateKbps:192, encoderPreset:'balanced' };
  const normalizeSettings = value => {const colorMode=value?.colorMode==='hdr-to-sdr'?'sdr':value?.colorMode||defaults.colorMode;const videoMode=value?.videoMode||defaults.videoMode;return {...defaults,...(value||{}),colorMode,...(['hdr10','hlg'].includes(colorMode)?{bitDepth:'10'}:{}),...(['prores','copy'].includes(videoMode)?{videoBitrateMbps:null}:{}),retryCount:1};};
  const preset = (id,name,settings) => ({ id,name,builtIn:true,settings:normalizeSettings(settings) });
  const builtInPresets = [
    preset('h264-compatible','H.264 通用兼容',{videoMode:'h264',colorMode:'sdr',bitDepth:'8',container:'mp4'}),
    preset('hevc-main10','HEVC Main10 · 跟随来源',{videoMode:'h265',colorMode:'auto',bitDepth:'10',container:'mp4',quality:'high'}),
    preset('hdr-to-sdr','Rec.709 SDR 输出',{videoMode:'h265',colorMode:'sdr',bitDepth:'8',container:'mp4'}),
    preset('av1-hardware','AV1 硬件高效',{videoMode:'av1',colorMode:'auto',bitDepth:'10',container:'mp4'}),
    preset('prores-master','ProRes 422 HQ 母版',{videoMode:'prores',colorMode:'auto',bitDepth:'10',container:'mov',quality:'high',audioMode:'copy'})
  ];
  const normalizePresets = value => (Array.isArray(value)?value:[]).slice(0,30).flatMap(item=>{const id=typeof item?.id==='string'?item.id.slice(0,80):'';const name=typeof item?.name==='string'?item.name.trim().slice(0,40):'';return id&&name&&item?.settings&&typeof item.settings==='object'?[{id,name,settings:normalizeSettings(item.settings)}]:[];});
  const readLegacyPresets = () => { try{return normalizePresets(JSON.parse(window.localStorage.getItem('photoflow:video-transcode-presets:v1')||'[]'));}catch{return [];} };
  const state = { context:null, paths:[], externalSources:[], settings:{...defaults}, settingsReady:mode!=='transcode', settingsTouched:false, customPresets:readLegacyPresets(), presetId:'', presetName:'', outputMode:'new', busy:false, paused:false, progress:0, message:mode==='transcode'?'等待选择视频':'等待输入...', mediaInfo:[], capabilities:null, estimate:0, inspectTimer:0, pasteOpen:false, dragActive:false, previewKey:'', previewLoading:false, previewError:'', sourcePreviews:{}, expandedSources:new Set() };
  const rpc = (method, payload={}) => api.rpc(method, payload);
  const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const icon = name => { const paths={folder:'<path d="M3 7h5l2 2h11v10H3z"/><path d="M3 7V5h6l2 2"/>',plus:'<path d="M12 5v14M5 12h14"/>',trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v5M14 11v5"/>',x:'<path d="m6 6 12 12M18 6 6 18"/>',chevron:'<path d="m9 18 6-6-6-6"/>',file:'<path d="M14 2H6a2 2 0 0 0-2 2v16h16V8z"/><path d="M14 2v6h6M9 13h6M12 10v6"/>'};return `<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||''}</svg>`; };
  const option = (value, label, current) => `<option value="${value}"${String(current)===String(value)?' selected':''}>${label}</option>`;
  const select = (label, name, values, disabled=false) => `<label>${label}<select data-field="${name}"${disabled?' disabled':''}>${values.map(item=>option(item[0],item[1],state.settings[name])).join('')}</select></label>`;
  const formatBytes = bytes => { const value=Number(bytes)||0; if(value<=0)return'0 B'; const units=['B','KiB','MiB','GiB','TiB']; const unit=Math.min(units.length-1,Math.floor(Math.log(value)/Math.log(1024))); const result=value/1024**unit; return `${result.toFixed(result>=100?0:result>=10?1:2)} ${units[unit]}`; };
  const sourceItems = () => [...state.paths.map(value=>({id:`project:${value}`,type:'project',value,name:value,kind:/\.[a-z0-9]{1,12}$/i.test(value)?'file':'folder'})),...state.externalSources.map(value=>({id:`external:${value.token}`,type:'external',value:value.token,name:value.name,kind:value.kind==='folder'?'folder':'file'}))];
  const sourceCount = () => sourceItems().length;
  const inputTokens = () => state.externalSources.map(item => item.token);
  const sourceDetails = item => { const normalized=String(item.name||'').replace(/[\\/]+$/,'');const parts=normalized.split(/[\\/]/).filter(Boolean);const name=parts.pop()||item.name;const extension=(name.match(/\.([^.]+)$/)||[])[1];return {name,badge:item.kind==='folder'?'目录':extension?extension.slice(0,5).toUpperCase():'文件',detail:item.kind==='folder'?'递归加入编码队列':(parts.slice(-2).join(' / ')||(item.type==='external'?'外部输入':item.name))}; };
  const sourceRows = () => sourceItems().map(item=>{const details=sourceDetails(item);const folder=item.kind==='folder';const preview=state.sourcePreviews[item.id];const expanded=state.expandedSources.has(item.id);const count=folder?`<span class="source-count">${state.previewLoading&&!preview?'正在读取…':state.previewError&&!preview?'读取失败':preview?`${preview.count} 个文件${preview.truncated?'+':''}`:'0 个文件'}</span>`:'';const toggle=folder?`<button class="source-toggle${expanded?' expanded':''}" type="button" data-toggle-source="${escape(item.id)}" aria-expanded="${expanded}" aria-label="${expanded?'收起':'展开'} ${escape(details.name)}" title="${expanded?'收起':'展开'}">${icon('chevron')}</button>`:'';const children=folder&&expanded?`<div class="source-children">${state.previewLoading&&!preview?'<p class="source-empty-row">正在读取文件夹中的媒体文件…</p>':state.previewError&&!preview?`<p class="source-error-row">${escape(state.previewError)}</p>`:preview?.files?.length?preview.files.map(file=>`<div class="source-child">${icon('file')}<span title="${escape(file)}">${escape(file)}</span></div>`).join(''):'<p class="source-empty-row">没有找到匹配的视频文件</p>'}${preview?.truncated?`<p class="source-truncated">文件较多，列表仅显示前 ${preview.files.length} 个。</p>`:''}</div>`:'';return `<div class="source-group"><div class="source-row"><span class="source-badge">${escape(details.badge)}</span><span class="source-copy"><span class="source-name" title="${escape(item.name)}">${escape(details.name)}</span><span class="source-detail" title="${escape(item.name)}">${escape(details.detail)}</span></span>${count}${toggle}<button class="source-remove" type="button" data-remove-source="${escape(item.id)}" aria-label="移除 ${escape(details.name)}" title="移除">${icon('x')}</button></div>${children}</div>`;}).join('');
  const sourceCard = title => { const count=sourceCount();const folderIds=sourceItems().filter(item=>item.kind==='folder').map(item=>item.id);const allExpanded=folderIds.length&&folderIds.every(id=>state.expandedSources.has(id));return `<section class="source-picker"><div class="source-picker-head"><div><p class="source-title">${title} ${count} 个来源</p><p class="source-description">文件夹会递归扫描，输出保留原子目录结构</p></div><div class="source-actions">${folderIds.length?`<button data-toggle-all>${allExpanded?'全部收起':'展开全部'}</button>`:''}<button data-choose="folder">${icon('folder')}追加文件夹</button><button data-choose="files">${icon('plus')}追加视频</button><button class="pf-button-danger clear-sources" data-clear-sources${count?'':' disabled'}>${icon('trash')}清空</button></div></div><div class="source-drop${state.dragActive?' drag-active':''}${count?' has-sources':''}">${count?`<div class="source-rows">${sourceRows()}</div>`:`<button class="source-empty" data-choose="files">${icon('folder')}<strong>拖入视频或文件夹</strong><span>${state.dragActive?'松开即可追加':'也可以使用上方按钮或批量粘贴路径'}</span></button>`}</div><section class="paste-section pf-panel-card"><button class="paste-toggle" type="button" data-paste-toggle aria-expanded="${state.pasteOpen}">${icon('chevron')}<span>批量粘贴路径</span></button>${state.pasteOpen?`<div class="paste-panel"><textarea data-paste-draft placeholder="每行一个项目内相对路径"></textarea><div class="paste-footer"><span>粘贴后会立即追加；手动输入可点击右侧按钮。</span><button type="button" data-paste-add>${icon('file')}添加这些路径</button></div></div>`:''}</section></section>`; };
  const blockingIssues = () => {if(mode!=='transcode')return[];const settings=state.settings;const issues=[];const hasHdr=state.mediaInfo.some(item=>item.hdr);if(settings.videoMode==='h264'&&['hdr10','hlg'].includes(settings.colorMode))issues.push('H.264 不支持 HDR 输出，请选择 HEVC、AV1 或 ProRes。');if(settings.videoMode==='h264'&&settings.bitDepth==='10')issues.push('H.264 不支持当前 10-bit 输出设置。');if(settings.videoMode==='h264'&&settings.colorMode==='auto'&&hasHdr)issues.push('H.264 无法保留队列中的 HDR；请选择 Rec.709 SDR 输出或更换编码。');if(settings.videoMode==='av1'&&state.capabilities&&!state.capabilities.av1Hardware)issues.push('当前设备未检测到 AV1 硬件编码器。');return issues;};
  const status = () => `<section class="status-card pf-panel-section"><div class="status-head"><span class="status-message">${escape(state.message)}</span><span class="percent">${Math.round(state.progress)}%</span></div><div class="progress"><span style="width:${Math.max(0,Math.min(100,state.progress))}%"></span></div><div class="actions" style="margin-top:12px"><span class="hint">任务关闭面板后仍会在任务中心继续</span><div>${state.busy&&mode==='transcode'?`<button data-control="${state.paused?'resume':'pause'}">${state.paused?'继续':'暂停'}</button> `:''}<button class="${state.busy?'pf-button-danger':'pf-button-primary'}" data-start${mode==='transcode'&&(!state.settingsReady||blockingIssues().length)?' disabled':''}>${state.busy?'取消任务':mode==='transcode'?'开始编码':`开始切割${sourceCount()>1?`（${sourceCount()} 项）`:''}`}</button></div></div></section>`;
  const table = () => !state.mediaInfo.length?'':`<div class="table-wrap"><table><thead><tr><th>文件</th><th>画面</th><th>色彩</th><th>轨道</th><th>预计输出</th></tr></thead><tbody>${state.mediaInfo.map(item=>`<tr><td>${escape(item.name)}</td><td>${escape(item.codec)} · ${escape(item.pixelFormat)}<br>${item.width}×${item.height} · ${item.frameRate} fps<br>SAR ${escape(item.sar)} / DAR ${escape(item.dar)} / ${item.rotation}°</td><td>${escape(item.hdrKind)} · ${item.bitDepth}-bit<br>${escape(item.primaries)}/${escape(item.transfer)}/${escape(item.matrix)}</td><td>音频 ${item.audioTracks} · 字幕 ${item.subtitleTracks}</td><td>${formatBytes(item.estimatedOutputBytes)}</td></tr>`).join('')}</tbody></table></div>`;
  const allPresets = () => [...builtInPresets,...state.customPresets];
  const presetBar = () => { const disabled=state.busy||!state.settingsReady;const selected=state.presetId;const canDelete=selected&&!builtInPresets.some(value=>value.id===selected);return `<section class="preset-bar"><label>编码预设<select data-preset-select${disabled?' disabled':''}><option value=""${selected?'':' selected'}>自定义设置</option>${allPresets().map(value=>`<option value="${escape(value.id)}"${selected===value.id?' selected':''}>${value.builtIn?'内置 · ':''}${escape(value.name)}</option>`).join('')}</select></label><label>保存为用户预设<input data-preset-name maxlength="40" value="${escape(state.presetName)}" placeholder="输入预设名称"${disabled?' disabled':''}></label><button type="button" class="pf-button-primary preset-action" data-preset-save${disabled||!state.presetName.trim()?' disabled':''}>保存</button><button type="button" class="preset-action" data-preset-delete${disabled||!canDelete?' disabled':''}>删除</button></section>`; };
  const persistSettings = (withPresets=false) => void rpc('video-tools.settings.update.v1',{settings:state.settings,...(withPresets?{presets:state.customPresets}:{})}).catch(error=>{state.message=error.message||String(error);render();});
  const applyPreset = id => { state.presetId=id;const selected=allPresets().find(value=>value.id===id);if(!selected){render();return;}state.settingsTouched=true;state.settingsReady=true;state.settings=normalizeSettings(selected.settings);render();persistSettings();scheduleInspect(); };
  const savePreset = () => { const name=state.presetName.trim();if(!name||state.busy||!state.settingsReady)return;const id=globalThis.crypto?.randomUUID?.()||`preset-${Date.now()}`;state.customPresets=[...state.customPresets,{id,name:name.slice(0,40),settings:{...state.settings}}].slice(-30);state.presetId=id;state.presetName='';render();persistSettings(true); };
  const deletePreset = () => { if(!state.presetId||builtInPresets.some(value=>value.id===state.presetId))return;state.customPresets=state.customPresets.filter(value=>value.id!==state.presetId);state.presetId='';render();persistSettings(true); };
  const renderTranscode = () => {
    const settings=state.settings; const copy=settings.videoMode==='copy';
    root.innerHTML = `<div class="stack">${sourceCard('编码队列来源')}${presetBar()}<div class="grid"><section class="section"><h3>输出与编码</h3><div class="settings" style="margin-top:12px">${select('输出封装','container',[['mp4','MP4'],['mov','MOV'],['mkv','MKV']],settings.videoMode==='prores')}${select('视频编码','videoMode',[['h264','H.264'],['h265','HEVC / H.265'],['av1','AV1 · 硬件'],['prores','Apple ProRes'],['copy','仅更换封装']])}${select('画质','quality',[['high','高质量'],['balanced','平衡'],['small','更小文件']],copy)}${select('编码速度','encoderPreset',[['fast','快速'],['balanced','平衡'],['quality','质量优先']],copy)}<label>自定义视频码率<input data-number="videoBitrateMbps" type="number" min="0.1" max="800" step="0.1" value="${settings.videoBitrateMbps??''}" placeholder="自动（Mbps）"${copy?' disabled':''}></label></div></section><section class="section"><h3>画面与色彩</h3><div class="settings" style="margin-top:12px">${select('分辨率','resolution',[['original','保持原分辨率'],['2160p','最长边 4K'],['1080p','最长边 1080p'],['720p','最长边 720p']],copy)}${select('色彩处理','colorMode',[['auto','自动识别并保留'],['sdr','Rec.709 SDR'],['hdr10','HDR10 · PQ/BT.2020'],['hlg','HLG · BT.2020'],['hdr-to-sdr','HDR 转 Rec.709 SDR']],copy)}${select('位深','bitDepth',[['auto','跟随来源'],['8','8-bit'],['10','10-bit']],copy)}${select('旋转','rotation',[['auto','自动应用来源方向'],['0','不旋转'],['90','顺时针 90°'],['180','180°'],['270','逆时针 90°']],copy)}${select('像素宽高比','aspectMode',[['preserve','保留 SAR/DAR'],['square-pixels','转为方形像素']],copy)}</div></section><section class="section"><h3>帧率</h3><div class="settings" style="margin-top:12px">${select('帧率模式','frameRateMode',[['preserve','保持时间戳'],['cfr','CFR 固定帧率'],['vfr','VFR 可变帧率']],copy)}${settings.frameRateMode==='cfr'?select('目标帧率','frameRate',[['original','来源帧率'],['24','24 fps'],['25','25 fps'],['30','30 fps'],['50','50 fps'],['60','60 fps']],copy):''}</div></section><section class="section"><h3>音频与字幕</h3><div class="settings" style="margin-top:12px">${select('音轨','audioTrack',[['all','全部音轨'],['first','仅第一音轨']],settings.audioMode==='remove')}${select('音频处理','audioMode',[['copy','复制编码'],['aac','AAC'],['remove','移除音频']])}${settings.audioMode==='aac'?select('AAC 码率','audioBitrateKbps',[[96,'96 kbps'],[128,'128 kbps'],[160,'160 kbps'],[192,'192 kbps'],[256,'256 kbps'],[320,'320 kbps']]):''}${select('字幕','subtitleMode',[['copy','复制字幕轨'],['burn','烧录第一字幕轨'],['remove','移除字幕']])}</div></section></div><div class="notice">${!state.settingsReady?'正在载入转码设置…':state.mediaInfo.length?`${state.mediaInfo.length} 个视频 · 预计输出 ${formatBytes(state.estimate)}`:sourceCount()?'正在自动更新预计输出…':'添加视频后自动估算预计输出'}</div>${table()}<div class="choices"><button class="choice ${state.outputMode==='new'?'active':''}" data-output="new"><strong>另存为新视频</strong><span>保存在原视频旁，文件名增加“_转码”；文件夹来源输出到新的“_转码”目录。</span></button><button class="choice ${state.outputMode==='delete-original'?'active':''}" data-output="delete-original"><strong>替换原视频</strong><span>结果校验通过后替换原视频，原视频移入回收站；失败时保留原视频。</span></button></div>${status()}</div>`;
    const field = name => root.querySelector(`[data-field="${name}"]`);
    const relabel = (element, text) => { const label=element?.closest('label');if(label?.firstChild)label.firstChild.textContent=text; };
    const renameOption = (element, value, text) => { const item=[...element?.options||[]].find(option=>option.value===value);if(item)item.textContent=text; };
    const videoMode=field('videoMode');renameOption(videoMode,'copy','复制视频流');
    const quality=field('quality');relabel(quality,settings.videoMode==='prores'?'ProRes 规格':'画质');if(quality)quality.disabled=copy||settings.videoBitrateMbps!==null;
    if(settings.videoMode==='prores'){renameOption(quality,'high','422 HQ');renameOption(quality,'balanced','422');renameOption(quality,'small','422 LT');}
    relabel(root.querySelector('[data-number="videoBitrateMbps"]'),'目标视频码率');
    const resolution=field('resolution');renameOption(resolution,'2160p','最大 4K');renameOption(resolution,'1080p','最大 1080p');renameOption(resolution,'720p','最大 720p');
    const color=field('colorMode');relabel(color,'输出色彩');renameOption(color,'auto','跟随来源');color?.querySelector('option[value="hdr-to-sdr"]')?.remove();
    const bitDepth=field('bitDepth');if(bitDepth)bitDepth.disabled=copy||settings.videoMode==='prores'||['hdr10','hlg'].includes(settings.colorMode);
    const issues=blockingIssues();if(issues.length)root.querySelector('.grid')?.insertAdjacentHTML('afterend',issues.map(message=>`<div class="notice">${escape(message)}</div>`).join(''));
  };
  const renderSplit = () => { const raw=state.paths[0]||state.externalSources[0]?.name||'视频.mp4';const outputName=sourceCount()===1?escape(raw.split(/[\\/]/).pop().replace(/(\.[^.]+)$/,'_part001$1')):sourceCount()>1?`按 ${sourceCount()} 个来源分别处理`:'视频名_part001.mp4';root.innerHTML=`<div class="stack">${sourceCard('已选择')}<div class="notice">原视频保持不变，分段文件写入原视频所在目录。</div><div class="split-summary"><div class="metric"><small>分段大小</small><strong>约 3.95 GB（固定）</strong></div><div class="metric"><small>输出名称</small><strong>${outputName}</strong></div></div>${status()}</div>`; };
  const render = () => { mode==='transcode'?renderTranscode():renderSplit();root.querySelectorAll('.section,.choice,.metric,.preset-bar').forEach(element=>element.classList.add('pf-panel-section')); };
  const refreshSourcePreviews = () => { const items=sourceItems();const key=items.map(item=>item.id).join('\n');const activeIds=new Set(items.map(item=>item.id));state.expandedSources=new Set([...state.expandedSources].filter(id=>activeIds.has(id)));if(key===state.previewKey){render();return;}state.previewKey=key;state.previewError='';state.sourcePreviews={};const folders=items.filter(item=>item.kind==='folder');if(!folders.length){state.previewLoading=false;render();return;}state.previewLoading=true;render();void rpc('video-tools.sources.preview.v1',{relativePaths:state.paths,inputTokens:inputTokens()}).then(result=>{if(state.previewKey!==key)return;state.previewLoading=false;state.sourcePreviews=Object.fromEntries((result.sourcePreviews||[]).flatMap(preview=>items[preview.sourceIndex]?.kind==='folder'?[[items[preview.sourceIndex].id,preview]]:[]));render();}).catch(error=>{if(state.previewKey!==key)return;state.previewLoading=false;state.previewError=error.message||String(error);render();}); };
  const scheduleInspect = () => { clearTimeout(state.inspectTimer);if(!state.context||!state.settingsReady||!sourceCount()||state.busy)return;state.inspectTimer=setTimeout(async()=>{try{state.message='正在自动更新预计输出…';render();const result=await rpc('video-tools.inspect.v1',{relativePaths:state.paths,inputTokens:inputTokens(),settings:state.settings});state.mediaInfo=result.mediaInfo||[];state.capabilities=result.capabilities||state.capabilities;state.estimate=result.estimatedOutputBytes||state.mediaInfo.reduce((sum,item)=>sum+(Number(item.estimatedOutputBytes)||0),0);state.message='预计输出已更新';}catch(error){state.message=error.message;}render();},400); };
  const start = async () => { if(state.busy){await rpc('video-tools.operation.control.v1',{processAction:mode==='transcode'?'video.transcode':'video.split',action:'cancel'}).catch(()=>{});state.message='正在取消…';render();return;}if(!sourceCount()||mode==='transcode'&&(!state.settingsReady||blockingIssues().length))return;state.busy=true;state.paused=false;state.progress=0;state.message=mode==='transcode'?'正在准备视频转码队列…':'正在扫描视频...';render();try{const method=mode==='transcode'?'video-tools.transcode.v1':'video-tools.split.v1';const result=await rpc(method,{idempotencyKey:crypto.randomUUID(),relativePaths:state.paths,inputTokens:inputTokens(),...(mode==='transcode'?{settings:state.settings,outputMode:state.outputMode}:{})});state.progress=100;state.message=mode==='transcode'?`技术校验完成：${result.report?.length||0} 个输出有效${result.failedCount?`，${result.failedCount} 个失败`:''}`:'视频切割完成';}catch(error){state.message=error.message;}finally{state.busy=false;state.paused=false;render();} };
  const appendExternalSources = values => { const existing=new Set(state.externalSources.map(item=>item.token));for(const item of values||[]){if(!item?.token||existing.has(item.token))continue;existing.add(item.token);state.externalSources.push({token:item.token,name:item.relativeName||item.name||'外部输入',kind:item.kind==='directory'||item.kind==='folder'?'folder':'file'});}state.externalSources=state.externalSources.slice(0,120); };
  const choose = async kind => { try{const result=await rpc('video-tools.sources.choose.v1',{kind});if(!result.cancelled)appendExternalSources(result.sources);refreshSourcePreviews();if(mode==='transcode')scheduleInspect();}catch(error){state.message=error.message;render();} };
  const addPastedProjectPaths = text => { const values=String(text||'').replace(/\0/g,'').split(/\r?\n|\s*;\s*/).map(value=>value.trim().replace(/^[“”"']+|[“”"']+$/g,'')).filter(Boolean);const safe=values.filter(value=>! /^(?:[a-z]:|[\\/])/i.test(value)&&!value.replace(/\\/g,'/').split('/').includes('..'));state.paths=[...new Set([...state.paths,...safe])].slice(0,120);if(safe.length!==values.length)state.message='插件中请粘贴当前项目内的相对路径；外部路径请使用选择按钮或拖放。'; };
  const applyContext = context => { state.context=context;state.paths=[...new Set(context.selectedRelativePaths||[])];document.documentElement.classList.toggle('dark',context.resolvedTheme==='dark');refreshSourcePreviews();if(mode==='transcode')scheduleInspect(); };
  document.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;if(target.dataset.start!==undefined)void start();else if(target.dataset.presetSave!==undefined)savePreset();else if(target.dataset.presetDelete!==undefined)deletePreset();else if(target.dataset.choose)void choose(target.dataset.choose==='folder'?'folder':'files');else if(target.dataset.output){state.outputMode=target.dataset.output;render();}else if(target.dataset.toggleAll!==undefined){const folders=sourceItems().filter(item=>item.kind==='folder').map(item=>item.id);const allExpanded=folders.every(id=>state.expandedSources.has(id));state.expandedSources=allExpanded?new Set():new Set(folders);render();}else if(target.dataset.toggleSource){const id=target.dataset.toggleSource;if(state.expandedSources.has(id))state.expandedSources.delete(id);else state.expandedSources.add(id);render();}else if(target.dataset.clearSources!==undefined){state.paths=[];state.externalSources=[];refreshSourcePreviews();if(mode==='transcode')scheduleInspect();}else if(target.dataset.removeSource){const id=target.dataset.removeSource;if(id.startsWith('project:'))state.paths=state.paths.filter(value=>`project:${value}`!==id);else state.externalSources=state.externalSources.filter(value=>`external:${value.token}`!==id);refreshSourcePreviews();if(mode==='transcode')scheduleInspect();}else if(target.dataset.pasteToggle!==undefined){state.pasteOpen=!state.pasteOpen;render();}else if(target.dataset.pasteAdd!==undefined){const textarea=document.querySelector('[data-paste-draft]');addPastedProjectPaths(textarea?.value);refreshSourcePreviews();if(mode==='transcode')scheduleInspect();}else if(target.dataset.control){state.paused=target.dataset.control==='pause';void rpc('video-tools.operation.control.v1',{processAction:'video.transcode',action:target.dataset.control});render();}});
  document.addEventListener('dragover',event=>{if(!event.target.closest?.('.source-drop')||!event.dataTransfer?.types?.includes('Files'))return;event.preventDefault();event.dataTransfer.dropEffect='copy';if(!state.dragActive){state.dragActive=true;render();}});
  document.addEventListener('dragleave',event=>{if(!state.dragActive||event.relatedTarget&&event.target.closest?.('.source-drop')?.contains(event.relatedTarget))return;state.dragActive=false;render();});
  document.addEventListener('drop',event=>{if(!event.target.closest?.('.source-drop'))return;event.preventDefault();state.dragActive=false;const files=event.dataTransfer?.files;if(!files?.length){render();return;}void api.authorizeFiles(files).then(result=>{appendExternalSources(result.inputs);refreshSourcePreviews();if(mode==='transcode')scheduleInspect();}).catch(error=>{state.message=error.message;render();});});
  document.addEventListener('input',event=>{const target=event.target;if(target.dataset.presetName!==undefined){state.presetName=target.value;const button=root.querySelector('[data-preset-save]');if(button)button.disabled=state.busy||!state.settingsReady||!state.presetName.trim();}});
  document.addEventListener('change',event=>{const target=event.target;if(target.dataset.presetSelect!==undefined){applyPreset(target.value);}else if(target.dataset.field){state.settingsTouched=true;state.settingsReady=true;state.presetId='';state.settings[target.dataset.field]=target.dataset.field==='audioBitrateKbps'?Number(target.value):target.value;if(target.dataset.field==='videoMode'&&target.value==='copy')Object.assign(state.settings,{resolution:'original',frameRate:'original',frameRateMode:'preserve',colorMode:'auto',bitDepth:'auto',rotation:'auto',aspectMode:'preserve',videoBitrateMbps:null});if(target.dataset.field==='videoMode'&&target.value==='prores')Object.assign(state.settings,{container:'mov',bitDepth:'10',videoBitrateMbps:null});if(target.dataset.field==='colorMode'&&['hdr10','hlg'].includes(target.value))state.settings.bitDepth='10';if(target.dataset.field==='frameRateMode'&&target.value!=='cfr')state.settings.frameRate='original';render();persistSettings();scheduleInspect();}else if(target.dataset.number){state.settingsTouched=true;state.settingsReady=true;state.presetId='';state.settings[target.dataset.number]=target.value?Number(target.value):null;render();persistSettings();scheduleInspect();}});
  api.onEvent('video-tools.operation.progress.v1',event=>{if((mode==='transcode'&&event.action!=='video.transcode')||(mode==='split'&&event.action!=='video.split'))return;state.progress=event.progress;state.message=event.message;state.busy=event.eventType!=='complete';render();});
  api.onThemeChange(value=>document.documentElement.classList.toggle('dark',value.resolvedTheme==='dark'));api.onContextChange(applyContext);
  render();
  void api.getContext().then(applyContext).catch(error=>{state.message=error.message;render();});
  if(mode==='transcode')void rpc('video-tools.settings.get.v1').then(result=>{if(!state.settingsTouched&&result?.settings)state.settings=normalizeSettings(result.settings);const storedPresets=normalizePresets(result?.presets);if(storedPresets.length||!state.customPresets.length)state.customPresets=storedPresets;else persistSettings(true);state.settingsReady=true;render();scheduleInspect();}).catch(error=>{state.settingsReady=true;state.message=error.message;render();scheduleInspect();});
  void rpc('video-tools.operation.current.v1',{processAction:mode==='transcode'?'video.transcode':'video.split'}).then(result=>{if(result.operation?.task&&!['completed','failed','cancelled'].includes(result.operation.task.state)){state.busy=true;state.progress=result.operation.task.progress||0;state.message=result.operation.task.message||state.message;render();}}).catch(error=>{state.message=error.message;render();});
})();
