const assert = require('node:assert/strict'); const crypto = require('node:crypto'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const readline = require('node:readline'); const { spawn } = require('node:child_process'); const { DatabaseSync } = require('node:sqlite');
const extensionRoot = path.resolve(__dirname, '..'); const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'video-transcription-service-')); const storageRoot = path.join(sandbox, 'storage'); fs.mkdirSync(storageRoot, { recursive: true });
const sources = { good: path.join(sandbox, 'good.mp4'), bad: path.join(sandbox, 'bad.wav'), slow: path.join(sandbox, 'slow.mkv') }; fs.writeFileSync(sources.good, '第一条字幕\n可搜索字幕'); fs.writeFileSync(sources.bad, 'FAIL_TRANSCRIPTION'); fs.writeFileSync(sources.slow, 'SLOW_TRANSCRIPTION\n稍后完成');
const processLog = path.join(sandbox, 'processes.log');
const child = spawn(process.execPath, [path.join(extensionRoot, 'service.cjs')], { cwd: extensionRoot, stdio: ['pipe', 'pipe', 'inherit'], env: { ...process.env, PHOTOFLOW_TRANSCRIBER_EXECUTABLE: process.execPath, PHOTOFLOW_TRANSCRIBER_ARGS_PREFIX: JSON.stringify([path.join(__dirname, 'fake-transcriber.cjs')]), PHOTOFLOW_TRANSCRIBER_PROCESS_LOG: processLog } });
const pending = new Map(); const requestProjects = new Map(); const tokens = new Map(); const projectMedia = new Map([['project-bad.wav', sources.bad]]); const taskState = new Map(); const stages = new Map(); const committedPaths = new Map(); const idempotency = new Map(); const capabilityCalls = []; const failTaskAction = new Map(); let materializeCount = 0; let nextSources = []; let readyResolve; const ready = new Promise(resolve => { readyResolve = resolve; });
const send = value => child.stdin.write(`${JSON.stringify(value)}\n`); let nextId = 1;
const request = (method, payload = {}, projectId = 'project-test') => new Promise((resolve, reject) => { const id = `req-${nextId++}`; pending.set(id, { resolve, reject }); requestProjects.set(id, projectId); send({ type: 'request', id, method, payload, context: { surface: 'project', projectId, projectName: projectId, selectedRelativePaths: [] } }); });
const capability = async frame => {
  const payload = frame.payload || {}; const projectId = requestProjects.get(frame.parentId) || 'project-test'; capabilityCalls.push({ method: frame.method, payload, projectId });
  if (frame.method === 'component.storage.v7') return { apiVersion: 7, dataPath: storageRoot, databasePath: path.join(storageRoot, 'storage.sqlite3'), projectId, ownership: 'component-private' };
  if (frame.method === 'component.settings.v7') return { apiVersion: 7, revision: 1, settings: { language: 'zh', model: 'tiny', device: 'cpu', computeType: 'int8', beamSize: 2, vadFilter: true, simplifyChinese: true, cpuFallback: true } };
  if (frame.method === 'project.media.variants.v7') { const relativePath = payload.relativePath; const source = projectMedia.get(relativePath); if (!source) throw new Error('media missing'); const token = `test-input:${crypto.randomUUID()}`; tokens.set(token, source); return { apiVersion: 7, input: { token, expiresAt: Date.now() + 60_000 }, variants: {} }; }
  if (frame.method === 'dialogs.v7' && ['openFiles', 'openDirectory'].includes(payload.kind)) {
    const inputs = nextSources.map((source, index) => { const token = `test-input:${crypto.randomUUID()}`; tokens.set(token, source); return { name: path.basename(source), relativeName: payload.kind === 'openDirectory' ? `nested/${path.basename(source)}` : path.basename(source), token, expiresAt: Date.now() + 60_000 }; });
    return { apiVersion: 7, cancelled: false, inputs };
  }
  if (frame.method === 'project.input.tokens.v7') { materializeCount += 1; const source = tokens.get(payload.token); if (!source) throw new Error('expired token'); const directory = path.join(storageRoot, 'inputs', crypto.randomUUID()); fs.mkdirSync(directory, { recursive: true }); const privatePath = path.join(directory, path.basename(source)); fs.copyFileSync(source, privatePath); return { apiVersion: 7, inputId: path.basename(directory), privatePath, byteLength: fs.statSync(privatePath).size }; }
  if (frame.method === 'tasks.v7') { const failureKey = `${projectId}:${payload.action}`; if (failTaskAction.get(failureKey)) { failTaskAction.delete(failureKey); throw Object.assign(new Error(`simulated tasks ${payload.action} failure`), { code: 'COMPONENT_HOST_INTERNAL' }); } const state = taskState.get(`${projectId}:${payload.operationId}`) || { cancelled: false, actions: [] }; state.actions.push(payload.action); if (payload.action === 'cancel') state.cancelled = true; if (payload.action === 'resume') state.cancelled = false; taskState.set(`${projectId}:${payload.operationId}`, state); return { apiVersion: 7, task: { state: payload.action }, cancelled: state.cancelled, checkpoint: payload.checkpoint || {} }; }
  if (frame.method === 'component.events.v7') return { apiVersion: 7, emitted: true };
  if (frame.method === 'project.output.v7') {
    if (payload.action === 'stage') { const stageId = crypto.randomUUID(); stages.set(stageId, { projectId }); return { apiVersion: 7, stageId, privatePath: path.join(storageRoot, 'stage'), expiresAt: Date.now() + 10000 }; }
    if (payload.action === 'write') { const bytes = Buffer.from(payload.base64, 'base64'); const sha256 = crypto.createHash('sha256').update(bytes).digest('hex'); const key = `${projectId}:${payload.outputRelativePath}`; const previous = committedPaths.get(key); if (payload.replace === true) { assert(payload.previousCommitId && payload.previousArtifactId && payload.expectedDigest, 'strict Host requires the complete replacement ownership triple'); assert(previous && previous.commitId === payload.previousCommitId && previous.artifactId === payload.previousArtifactId && previous.sha256 === payload.expectedDigest, 'strict Host rejects stale or foreign replacement ownership'); } else { assert.equal(payload.replace, undefined, 'first publication omits replace'); if (previous) throw new Error('output conflict'); } const artifactId = crypto.randomUUID(); stages.set(payload.stageId, { projectId, artifactId, relativePath: payload.outputRelativePath, sha256, size: bytes.length, key }); return { apiVersion: 7, stageId: payload.stageId, artifactId, byteLength: bytes.length, sha256 }; }
    if (payload.action === 'validate') return { apiVersion: 7, stageId: payload.stageId, valid: true, fileCount: 1, totalBytes: 10 };
    if (payload.action === 'commit') { const idemKey = `${projectId}:${payload.idempotencyKey}`; if (idempotency.has(idemKey)) return idempotency.get(idemKey); const value = stages.get(payload.stageId); const receipt = { apiVersion: 7, commitId: crypto.randomUUID(), idempotencyKey: payload.idempotencyKey, outputs: [{ artifactId: value.artifactId, relativePath: value.relativePath, sha256: value.sha256, size: value.size }] }; committedPaths.set(value.key, { ...receipt.outputs[0], commitId: receipt.commitId }); idempotency.set(idemKey, receipt); return receipt; }
    if (payload.action === 'rollback') return { apiVersion: 7, stageId: payload.stageId, rolledBack: true };
  }
  if (frame.method === 'dialogs.v7' && ['openOutput', 'revealOutput'].includes(payload.kind)) return { apiVersion: 7, opened: true, outputRef: { commitId: payload.commitId, artifactId: payload.artifactId } };
  throw new Error(`Unhandled capability ${frame.method}`);
};
readline.createInterface({ input: child.stdout, crlfDelay: Infinity }).on('line', line => {
  const frame = JSON.parse(line);
  if (frame.type === 'ready') { readyResolve(); return; }
  if (frame.type === 'response') { const item = pending.get(frame.id); if (!item) return; pending.delete(frame.id); requestProjects.delete(frame.id); frame.ok ? item.resolve(frame.result) : item.reject(new Error(frame.error)); return; }
  if (frame.type === 'capability') Promise.resolve(capability(frame)).then(result => send({ type: 'capability-response', id: frame.id, ok: true, result }), error => send({ type: 'capability-response', id: frame.id, ok: false, error: error.message, errorCode: error.code || 'COMPONENT_HOST_INTERNAL' }));
});
const assertPublic = value => { const serialized = JSON.stringify(value); assert(!serialized.includes(sandbox), 'renderer response exposed a private absolute path'); assert(!/[A-Za-z]:\\/.test(serialized), 'renderer response exposed a Windows absolute path'); assert(!serialized.includes('private_path')); };
(async () => {
  try {
    await ready;
    nextSources = [sources.good]; const completedStart = await request('transcript.inputs.start.v1', { mode: 'file' }); assert(completedStart.operationId); assert.equal(materializeCount, 1, 'start consumes and materializes every external token before returning'); tokens.clear(); assertPublic(completedStart); const completed = await request('transcript.operation.run.v1', { operationId: completedStart.operationId }); assert.equal(completed.state, 'completed'); assert.equal(completed.succeeded, 1); assert(taskState.get(`project-test:${completed.id}`).actions.includes('complete')); assertPublic(completed);
    const verificationDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const completedPrivate = verificationDb.prepare('SELECT private_path,srt_path FROM transcript_files WHERE id=?').get(completed.files[0].id); assert.equal(completedPrivate.private_path, '', 'successful transcription removes the materialized full-media copy'); assert(fs.existsSync(completedPrivate.srt_path), 'SRT remains after media cleanup'); verificationDb.close();
    const detail = await request('transcript.file.get.v1', { fileId: completed.files[0].id }); assert.equal(detail.segments.length, 2); assert.equal(detail.segments[0].text, '第一条字幕'); assertPublic(detail);
    const searched = await request('transcript.search.v1', { query: '搜索' }); assert.equal(searched.results.length, 1); assert.equal(searched.results[0].fileId, completed.files[0].id); assertPublic(searched);
    const published = await request('transcript.output.publish.v1', { fileId: completed.files[0].id }); assert.equal(published.published, true); assert.equal(published.output.controlled, true); assert.match(published.output.sha256, /^[a-f0-9]{64}$/); assert(published.output.size > 0); assert.match(published.message, /无法原路旁写/); assertPublic(published); assert((await request('transcript.output.open.v1', { fileId: completed.files[0].id })).opened);
    const stageCalls = capabilityCalls.filter(call => call.method === 'project.output.v7' && call.payload.action === 'stage').length; const repeated = await request('transcript.output.publish.v1', { fileId: completed.files[0].id }); assert.equal(repeated.idempotent, true); assert.equal(capabilityCalls.filter(call => call.method === 'project.output.v7' && call.payload.action === 'stage').length, stageCalls, 'same-content retry does not leak another stage');
    const editDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const srtPath = editDb.prepare('SELECT srt_path FROM transcript_files WHERE id=?').get(completed.files[0].id).srt_path; fs.appendFileSync(srtPath, '\nedited'); editDb.close(); const replaced = await request('transcript.output.publish.v1', { fileId: completed.files[0].id }); assert.notEqual(replaced.output.sha256, published.output.sha256, 'changed content performs a controlled digest-bound replacement');

    const beforeBatchProcesses = fs.existsSync(processLog) ? fs.readFileSync(processLog, 'utf8').trim().split(/\r?\n/).filter(Boolean).length : 0;
    nextSources = [sources.good, sources.bad, sources.good]; const beforeMaterialize = materializeCount; const partialStart = await request('transcript.inputs.start.v1', { mode: 'files' }); assert.equal(materializeCount - beforeMaterialize, 3); tokens.clear(); const partial = await request('transcript.operation.run.v1', { operationId: partialStart.operationId }); assert.equal(partial.state, 'partial_failure'); assert.equal(partial.succeeded, 2); assert.equal(partial.failed, 1); assert.equal(partial.files.length, 3); assert(taskState.get(`project-test:${partial.id}`).actions.at(-1) === 'complete', 'partial failure reaches task completion only after every file'); const afterBatchProcesses = fs.readFileSync(processLog, 'utf8').trim().split(/\r?\n/).filter(Boolean).length; assert.equal(afterBatchProcesses - beforeBatchProcesses, 1, 'one operation reuses one persistent algorithm process/model across all files'); assertPublic(partial);
    const partialDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const partialRows = partialDb.prepare('SELECT state,private_path FROM transcript_files WHERE operation_id=? ORDER BY ordinal').all(partial.id); assert(partialRows.filter(row => row.state === 'completed').every(row => row.private_path === '')); assert(partialRows.find(row => row.state === 'failed').private_path, 'failed external input is retained for explicit resume'); partialDb.close();

    const sensitiveBefore = capabilityCalls.filter(call => call.projectId === 'project-other' && ['tasks.v7', 'project.output.v7', 'dialogs.v7'].includes(call.method)).length;
    assert.deepEqual((await request('transcript.operation.list.v1', {}, 'project-other')).operations, []); assert.deepEqual((await request('transcript.search.v1', { query: '搜索' }, 'project-other')).results, []);
    for (const [method, payload] of [['transcript.operation.get.v1', { operationId: completed.id }], ['transcript.operation.run.v1', { operationId: completed.id }], ['transcript.operation.cancel.v1', { operationId: completed.id }], ['transcript.operation.resume.v1', { operationId: completed.id }], ['transcript.file.get.v1', { fileId: completed.files[0].id }], ['transcript.output.publish.v1', { fileId: completed.files[0].id }], ['transcript.output.open.v1', { fileId: completed.files[0].id }]]) await assert.rejects(request(method, payload, 'project-other'), /找不到|尚未生成|请先发布/);
    assert.equal(capabilityCalls.filter(call => call.projectId === 'project-other' && ['tasks.v7', 'project.output.v7', 'dialogs.v7'].includes(call.method)).length, sensitiveBefore, 'cross-project IDs never reach tasks, output, or media-reference capabilities');

    nextSources = [sources.good]; const conflictStart = await request('transcript.inputs.start.v1', { mode: 'file' }); const conflictDone = await request('transcript.operation.run.v1', { operationId: conflictStart.operationId }); const conflictPath = `project-test:视频字幕/${conflictDone.id}/good.srt`; committedPaths.set(conflictPath, { commitId: crypto.randomUUID(), artifactId: crypto.randomUUID(), sha256: 'a'.repeat(64) }); await assert.rejects(request('transcript.output.publish.v1', { fileId: conflictDone.files[0].id }), /output conflict/, 'foreign pre-existing output remains a conflict');

    for (const action of ['resume', 'status', 'report', 'complete']) {
      nextSources = [sources.good]; const retryStart = await request('transcript.inputs.start.v1', { mode: 'file' }); failTaskAction.set(`project-test:${action}`, true); await assert.rejects(request('transcript.operation.run.v1', { operationId: retryStart.operationId }), /simulated tasks/); const retry = await request('transcript.operation.run.v1', { operationId: retryStart.operationId }); assert.notEqual(retry.alreadyRunning, true, `${action} failure must not poison runningOperations`); assert.equal(retry.state, 'completed');
    }
    nextSources = [sources.bad]; const failRetryStart = await request('transcript.inputs.start.v1', { mode: 'file' }); failTaskAction.set('project-test:fail', true); await assert.rejects(request('transcript.operation.run.v1', { operationId: failRetryStart.operationId }), /simulated tasks fail/); const failRetry = await request('transcript.operation.run.v1', { operationId: failRetryStart.operationId }); assert.notEqual(failRetry.alreadyRunning, true); assert.equal(failRetry.state, 'failed');

    const projectStart = await request('transcript.project.start.v1', { scope: 'selection', relativePaths: ['project-bad.wav'] }); const beforeProjectMaterialize = materializeCount; const projectFailed = await request('transcript.operation.run.v1', { operationId: projectStart.operationId }); assert.equal(projectFailed.state, 'failed'); assert.equal(materializeCount, beforeProjectMaterialize + 1); const projectDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const projectRow = projectDb.prepare('SELECT private_path,media_ref_json FROM transcript_files WHERE operation_id=?').get(projectStart.operationId); assert.equal(projectRow.private_path, '', 'failed project media copy is deleted'); assert.match(projectRow.media_ref_json, /project-bad\.wav/, 'project media reference is retained for reauthorization'); projectDb.close(); projectMedia.set('project-bad.wav', sources.good); await request('transcript.operation.resume.v1', { operationId: projectStart.operationId }); const projectRecovered = await request('transcript.operation.run.v1', { operationId: projectStart.operationId }); assert.equal(projectRecovered.state, 'completed'); assert.equal(materializeCount, beforeProjectMaterialize + 2, 'project media retry obtains a fresh one-time token');

    const cleanupRoot = path.join(sandbox, 'cleanup-storage'); const cleanupInputs = path.join(cleanupRoot, 'inputs', 'one'); const cleanupSubtitles = path.join(cleanupRoot, 'subtitles'); fs.mkdirSync(cleanupInputs, { recursive: true }); fs.mkdirSync(cleanupSubtitles, { recursive: true }); const cleanupDb = path.join(cleanupRoot, 'storage.sqlite3'); const cleanupMedia = path.join(cleanupInputs, 'media.mp4'); const cleanupSrt = path.join(cleanupSubtitles, 'keep.srt'); const outside = path.join(sandbox, 'outside.mp4'); fs.writeFileSync(cleanupDb, 'db'); fs.writeFileSync(cleanupMedia, 'media'); fs.writeFileSync(cleanupSrt, 'srt'); fs.writeFileSync(outside, 'outside'); const { removePrivateInput } = require('../service.cjs'); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, cleanupSrt), false); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, cleanupDb), false); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, outside), false); assert(fs.existsSync(cleanupSrt) && fs.existsSync(cleanupDb) && fs.existsSync(outside)); let linked = ''; try { linked = path.join(cleanupRoot, 'inputs', 'linked.mp4'); fs.symlinkSync(outside, linked, 'file'); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, linked), false); assert(fs.existsSync(outside)); } catch (error) { if (!['EPERM', 'EACCES'].includes(error.code)) throw error; } assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, cleanupMedia), true); assert(!fs.existsSync(cleanupMedia));

    nextSources = [sources.slow]; const cancelStart = await request('transcript.inputs.start.v1', { mode: 'folder' }); const running = request('transcript.operation.run.v1', { operationId: cancelStart.operationId }); await new Promise(resolve => setTimeout(resolve, 180)); const cancelled = await request('transcript.operation.cancel.v1', { operationId: cancelStart.operationId }); assert.equal(cancelled.state, 'cancelled'); const cancelledRun = await running; assert.equal(cancelledRun.state, 'cancelled'); assert(taskState.get(`project-test:${cancelStart.operationId}`).actions.includes('cancel')); assertPublic(cancelledRun);
    const resumed = await request('transcript.operation.resume.v1', { operationId: cancelStart.operationId }); assert.equal(resumed.accepted, true); assert.equal(resumed.operationId, cancelStart.operationId); const resumedRun = await request('transcript.operation.run.v1', { operationId: cancelStart.operationId }); assert.equal(resumedRun.state, 'completed'); assert.equal(resumedRun.succeeded, 1);
    console.log('video-transcription service project isolation, eager materialization, cleanup, persistent engine, failure recovery, cancel, search, and strict publish tests passed');
  } finally { child.kill(); fs.rmSync(sandbox, { recursive: true, force: true }); }
})().catch(error => { console.error(error); child.kill(); fs.rmSync(sandbox, { recursive: true, force: true }); process.exitCode = 1; });
