const assert = require('node:assert/strict'); const crypto = require('node:crypto'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const readline = require('node:readline'); const { spawn } = require('node:child_process'); const { DatabaseSync } = require('node:sqlite');
const extensionRoot = path.resolve(__dirname, '..'); const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'video-transcription-service-')); const storageRoot = path.join(sandbox, 'storage'); fs.mkdirSync(storageRoot, { recursive: true });
const testModelRoot = path.join(extensionRoot, 'models', 'tiny'); const createdTestModel = !fs.existsSync(testModelRoot); if (createdTestModel) { fs.mkdirSync(testModelRoot, { recursive: true }); for (const name of ['config.json', 'model.bin', 'tokenizer.json']) fs.writeFileSync(path.join(testModelRoot, name), name === 'model.bin' ? 'fixture' : '{}'); }
const sources = { good: path.join(sandbox, 'good.mp4'), bad: path.join(sandbox, 'bad.mp4'), slow: path.join(sandbox, 'slow.mkv'), long: path.join(sandbox, 'long.mp4') }; fs.writeFileSync(sources.good, '第一条字幕\n可搜索字幕'); fs.writeFileSync(sources.bad, 'FAIL_TRANSCRIPTION'); fs.writeFileSync(sources.slow, 'SLOW_TRANSCRIPTION\n稍后完成'); fs.writeFileSync(sources.long, Array.from({ length: 450 }, (_, index) => index === 319 ? '深页搜索命中' : `字幕 ${index + 1}`).join('\n'));
const processLog = path.join(sandbox, 'processes.log');
const child = spawn(process.execPath, [path.join(extensionRoot, 'service.cjs')], { cwd: extensionRoot, stdio: ['pipe', 'pipe', 'inherit'], env: { ...process.env, PHOTOFLOW_TRANSCRIBER_EXECUTABLE: process.execPath, PHOTOFLOW_TRANSCRIBER_ARGS_PREFIX: JSON.stringify([path.join(__dirname, 'fake-transcriber.cjs')]), PHOTOFLOW_TRANSCRIBER_PROCESS_LOG: processLog } });
const pending = new Map(); const requestProjects = new Map(); const tokens = new Map(); const projectMedia = new Map(); const mediaItems = []; const taskState = new Map(); const stages = new Map(); const committedPaths = new Map(); const idempotency = new Map(); const capabilityCalls = []; const failTaskAction = new Map(); let cancelNextPublishReport = false; let materializeCount = 0; let generatedSelection = 0; let mediaPageOffset = 0; let readyResolve; const ready = new Promise(resolve => { readyResolve = resolve; });
const send = value => child.stdin.write(`${JSON.stringify(value)}\n`); let nextId = 1;
const request = (method, payload = {}, projectId = 'project-test', selection = [], scopeRelativePath = '') => new Promise((resolve, reject) => { const id = `req-${nextId++}`; pending.set(id, { resolve, reject }); requestProjects.set(id, projectId); send({ type: 'request', id, method, payload, context: { surface: 'project', projectId, projectName: projectId, scopeRelativePath, selectedRelativePaths: selection } }); });
const addProjectMedia = (relativePath, source, extra = {}) => { projectMedia.set(relativePath.toLowerCase(), source); mediaItems.push({ name: path.posix.basename(relativePath), relativePath, mediaRef: { relativePath }, ...extra }); };
const startSelectedSources = sourcesToAdd => { const folder = `generated/${++generatedSelection}`; const selection = sourcesToAdd.map((source, index) => { const relativePath = `${folder}/${index}-${path.basename(source)}`; addProjectMedia(relativePath, source); return relativePath; }); return request('transcript.project.start.v1', { relativePaths: selection, scopeRelativePath: folder }); };
addProjectMedia('project-bad.mp4', sources.bad);
const capability = async frame => {
  const payload = frame.payload || {}; const projectId = requestProjects.get(frame.parentId) || 'project-test'; capabilityCalls.push({ method: frame.method, payload, projectId });
  if (frame.method === 'component.storage.v7') return { apiVersion: 7, dataPath: storageRoot, databasePath: path.join(storageRoot, 'storage.sqlite3'), projectId, ownership: 'component-private' };
  if (frame.method === 'component.settings.v7') return { apiVersion: 7, revision: 1, settings: { language: 'zh', model: 'tiny', device: 'cpu', computeType: 'int8', beamSize: 2, vadFilter: true, simplifyChinese: true, cpuFallback: true } };
  if (frame.method === 'project.media.page.v7') { assert.deepEqual(payload.kinds, ['video'], 'Host V7 media.page accepts only the declared video kind'); if (!payload.cursor) mediaPageOffset = 0; const videos = mediaItems.filter(item => /\.(?:mp4|mov|mkv|avi|webm|m4v|mpg|mpeg|mts|m2ts|wmv|flv)$/i.test(item.relativePath)); const pageSize = Math.min(2, Number(payload.pageSize) || 2); const items = videos.slice(mediaPageOffset, mediaPageOffset + pageSize); mediaPageOffset += items.length; const hasMore = mediaPageOffset < videos.length; return { apiVersion: 7, items, page: { hasMore, cursor: hasMore ? 'host-session-cursor' : null } }; }
  if (frame.method === 'project.media.variants.v7') { const relativePath = payload.relativePath; const source = projectMedia.get(String(relativePath).toLowerCase()); if (!source) throw new Error('media missing'); const token = `test-input:${crypto.randomUUID()}`; tokens.set(token, source); return { apiVersion: 7, input: { token, expiresAt: Date.now() + 60_000 }, variants: {} }; }
  if (frame.method === 'project.input.tokens.v7') { materializeCount += 1; const source = tokens.get(payload.token); if (!source) throw new Error('expired token'); const directory = path.join(storageRoot, 'inputs', crypto.randomUUID()); fs.mkdirSync(directory, { recursive: true }); const privatePath = path.join(directory, path.basename(source)); fs.copyFileSync(source, privatePath); return { apiVersion: 7, inputId: path.basename(directory), privatePath, byteLength: fs.statSync(privatePath).size }; }
  if (frame.method === 'tasks.v7') { const failureKey = `${projectId}:${payload.action}`; if (failTaskAction.get(failureKey)) { failTaskAction.delete(failureKey); throw Object.assign(new Error(`simulated tasks ${payload.action} failure`), { code: 'COMPONENT_HOST_INTERNAL' }); } const state = taskState.get(`${projectId}:${payload.operationId}`) || { cancelled: false, actions: [] }; state.actions.push(payload.action); if (payload.action === 'cancel') state.cancelled = true; if (payload.action === 'resume') state.cancelled = false; if (cancelNextPublishReport && payload.action === 'report' && String(payload.operationId).startsWith('publish-')) { state.cancelled = true; cancelNextPublishReport = false; } taskState.set(`${projectId}:${payload.operationId}`, state); return { apiVersion: 7, task: { state: payload.action }, cancelled: state.cancelled, checkpoint: payload.checkpoint || {} }; }
  if (frame.method === 'component.events.v7') return { apiVersion: 7, emitted: true };
  if (frame.method === 'project.output.v7') {
    if (payload.action === 'stage') { const stageId = crypto.randomUUID(); stages.set(stageId, { projectId }); return { apiVersion: 7, stageId, privatePath: path.join(storageRoot, 'stage'), expiresAt: Date.now() + 10000 }; }
    if (payload.action === 'write') { const bytes = Buffer.from(payload.base64, 'base64'); const sha256 = crypto.createHash('sha256').update(bytes).digest('hex'); const key = `${projectId}:${payload.outputRelativePath}`; const previous = committedPaths.get(key); if (payload.replace === true) { assert(payload.previousCommitId && payload.previousArtifactId && payload.expectedDigest, 'strict Host requires the complete replacement ownership triple'); assert(previous && previous.commitId === payload.previousCommitId && previous.artifactId === payload.previousArtifactId && previous.sha256 === payload.expectedDigest, 'strict Host rejects stale or foreign replacement ownership'); } else { assert.equal(payload.replace, undefined, 'first publication omits replace'); if (previous) throw new Error('output conflict'); } const artifactId = crypto.randomUUID(); stages.set(payload.stageId, { projectId, artifactId, relativePath: payload.outputRelativePath, sha256, size: bytes.length, key }); return { apiVersion: 7, stageId: payload.stageId, artifactId, byteLength: bytes.length, sha256 }; }
    if (payload.action === 'validate') return { apiVersion: 7, stageId: payload.stageId, valid: true, fileCount: 1, totalBytes: 10 };
    if (payload.action === 'commit') { assert.match(payload.idempotencyKey, /^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/, 'strict Host enforces the project.output.v7 id contract'); const idemKey = `${projectId}:${payload.idempotencyKey}`; if (idempotency.has(idemKey)) return idempotency.get(idemKey); const value = stages.get(payload.stageId); const receipt = { apiVersion: 7, commitId: crypto.randomUUID(), idempotencyKey: payload.idempotencyKey, outputs: [{ artifactId: value.artifactId, relativePath: value.relativePath, sha256: value.sha256, size: value.size }] }; committedPaths.set(value.key, { ...receipt.outputs[0], commitId: receipt.commitId }); idempotency.set(idemKey, receipt); return receipt; }
    if (payload.action === 'rollback') return { apiVersion: 7, stageId: payload.stageId, rolledBack: true };
  }
  if (frame.method === 'dialogs.v7' && ['openOutput', 'revealOutput'].includes(payload.kind)) return { apiVersion: 7, opened: true, outputRef: { commitId: payload.commitId, artifactId: payload.artifactId } };
  throw new Error(`Unhandled capability ${frame.method}`);
};
readline.createInterface({ input: child.stdout, crlfDelay: Infinity }).on('line', line => {
  const frame = JSON.parse(line);
  if (frame.type === 'ready') { readyResolve(); return; }
  if (frame.type === 'response') { const item = pending.get(frame.id); if (!item) return; pending.delete(frame.id); requestProjects.delete(frame.id); frame.ok ? item.resolve(frame.result) : item.reject(new Error(frame.error)); return; }
  if (frame.type === 'capability') Promise.resolve(capability(frame)).then(result => send({ type: 'capability-response', id: frame.id, ok: true, result }), error => send({ type: 'capability-response', id: frame.id, ok: false, error: error.message, errorCode: error.code || 'COMPONENT_HOST_INTERNAL' }));
});
const assertPublic = value => { const serialized = JSON.stringify(value); assert(!serialized.includes(sandbox), 'renderer response exposed a private absolute path'); assert(!/[A-Za-z]:\\/.test(serialized), 'renderer response exposed a Windows absolute path'); assert(!serialized.includes('private_path')); };
(async () => {
  try {
    await ready;
    const models = await request('transcript.models.list.v1'); assert(models.models.some(item => item.id === 'tiny' && item.installed)); assert.equal(models.placement, 'models/<model-id>'); assert(!JSON.stringify(models).includes(extensionRoot), 'model discovery does not expose absolute paths'); await assert.rejects(request('transcript.settings.update.v1', { model: 'repo/name' }), /不支持/); await assert.rejects(request('transcript.settings.update.v1', { model: 'base' }), /未安装/);
    const heldModel = `${testModelRoot}.held`; const taskCallsBeforeMissingModel = capabilityCalls.filter(call => call.method === 'tasks.v7').length; fs.renameSync(testModelRoot, heldModel); try { await assert.rejects(request('transcript.project.start.v1', { relativePaths: ['project-bad.mp4'] }), /模型 tiny 未安装/); assert.equal(capabilityCalls.filter(call => call.method === 'tasks.v7').length, taskCallsBeforeMissingModel, 'missing model fails before creating a Host task'); } finally { fs.renameSync(heldModel, testModelRoot); }
    await assert.rejects(request('transcript.inputs.start.v1', { mode: 'file' }), /未知/, 'legacy external file-picker RPC is not exposed');
    assert.equal(capabilityCalls.filter(call => call.method === 'dialogs.v7').length, 0, 'starting work never opens a file dialog');
    addProjectMedia('Library/Clip.MP4', sources.good);
    addProjectMedia('Library/Folder/a.mp4', sources.good);
    addProjectMedia('Library/Folder/Nested/b.MOV', sources.good);
    addProjectMedia('Library/Folderish/not-selected.mp4', sources.good);
    addProjectMedia('Library/Folder/Nested/voice.WAV', sources.good);
    addProjectMedia('Library/Folder/photo.jpg', sources.good);
    addProjectMedia('Library/Second/c.mkv', sources.good);
    mediaItems.push({ ...mediaItems.find(item => item.relativePath === 'Library/Folder/a.mp4') });
    const previewSideEffectsBefore = { materializeCount, sensitiveCalls: capabilityCalls.filter(call => ['component.storage.v7', 'component.settings.v7', 'project.media.variants.v7', 'project.input.tokens.v7', 'tasks.v7'].includes(call.method)).length };
    const folderPreview = await request('transcript.selection.preview.v1', { relativePaths: ['Library/Folder'], scopeRelativePath: 'Library' });
    assert.deepEqual(folderPreview.files.map(file => file.relativeName), ['Library/Folder/a.mp4', 'Library/Folder/Nested/b.MOV'], 'folder preview recursively lists video descendants without Folderish siblings');
    const multiFilePreview = await request('transcript.selection.preview.v1', { relativePaths: ['Library/Clip.MP4', 'Library/Second/c.mkv'], scopeRelativePath: 'Library' });
    assert.deepEqual(multiFilePreview.files.map(file => file.relativeName), ['Library/Clip.MP4', 'Library/Second/c.mkv'], 'multiple selected files are previewed together');
    const mixedPreview = await request('transcript.selection.preview.v1', { relativePaths: ['Library/Clip.MP4', 'Library/Folder', 'Library/Folder/photo.jpg'], scopeRelativePath: 'Library' });
    assert.deepEqual(mixedPreview.files.map(file => file.relativeName), ['Library/Clip.MP4', 'Library/Folder/a.mp4', 'Library/Folder/Nested/b.MOV'], 'mixed preview lists only selected videos and recursive folder videos');
    assert.equal(mixedPreview.total, 3); assert.equal(mixedPreview.limit, 2000); assert.equal(mixedPreview.limitReached, false); assert(mixedPreview.files.every(file => Object.keys(file).sort().join(',') === 'displayName,relativeName'), 'preview exposes only redacted relative display data');
    const limitedPreview = await request('transcript.selection.preview.v1', { relativePaths: Array.from({ length: 2001 }, () => 'Library/Clip.MP4'), scopeRelativePath: 'Library' }); assert.equal(limitedPreview.limitReached, true, 'preview reports when its bounded 2000-selection ceiling is reached');
    assert.equal(materializeCount, previewSideEffectsBefore.materializeCount, 'selection preview never materializes media');
    assert.equal(capabilityCalls.filter(call => ['component.storage.v7', 'component.settings.v7', 'project.media.variants.v7', 'project.input.tokens.v7', 'tasks.v7'].includes(call.method)).length, previewSideEffectsBefore.sensitiveCalls, 'selection preview does not create storage, settings, variant, token, or task side effects');
    const exactSelection = await request('transcript.project.start.v1', { relativePaths: ['library/clip.mp4'], scopeRelativePath: 'LIBRARY' });
    assert.deepEqual(exactSelection.operation.files.map(file => file.relativeName), ['Library/Clip.MP4'], 'selected video matching follows Windows case-insensitive semantics');
    const folderSelection = await request('transcript.project.start.v1', { relativePaths: ['Library/Folder'], scopeRelativePath: 'Library' });
    assert.deepEqual(folderSelection.operation.files.map(file => file.relativeName), ['Library/Folder/a.mp4', 'Library/Folder/Nested/b.MOV'], 'selected folder recursively processes only Host video descendants, excludes same-prefix siblings, and remains deduplicated');
    const foldersSelection = await request('transcript.project.start.v1', { relativePaths: ['Library/Folder', 'Library/Second'], scopeRelativePath: 'Library' });
    assert.deepEqual(foldersSelection.operation.files.map(file => file.relativeName), ['Library/Folder/a.mp4', 'Library/Folder/Nested/b.MOV', 'Library/Second/c.mkv'], 'multiple selected folders share one bounded paginated video scan');
    const mixedSelection = await request('transcript.project.start.v1', { relativePaths: ['Library/Clip.MP4', 'Library/Folder', 'Library/Folder/photo.jpg'], scopeRelativePath: 'Library' });
    assert.deepEqual(mixedSelection.operation.files.map(file => file.relativeName), ['Library/Clip.MP4', 'Library/Folder/a.mp4', 'Library/Folder/Nested/b.MOV'], 'mixed selection processes videos and ignores images, audio, and unrelated files');
    assert(capabilityCalls.filter(call => call.method === 'project.media.page.v7').every(call => JSON.stringify(call.payload.kinds) === '["video"]'), 'every paginated media request is strictly video-only');
    await assert.rejects(request('transcript.project.start.v1', { relativePaths: [], scopeRelativePath: 'Library' }), /当前选择中没有可处理/);
    await assert.rejects(request('transcript.project.start.v1', { relativePaths: ['../Library/Clip.MP4'] }), /当前选择中没有可处理/);
    await assert.rejects(request('transcript.project.start.v1', { relativePaths: ['Other/clip.mp4'], scopeRelativePath: 'Library' }), /超出文件页面范围/);
    const completedStart = await startSelectedSources([sources.good]); assert(completedStart.operationId); assertPublic(completedStart); const completed = await request('transcript.operation.run.v1', { operationId: completedStart.operationId }); assert.equal(completed.state, 'completed'); assert.equal(completed.succeeded, 1); assert(taskState.get(`project-test:${completed.id}`).actions.includes('complete')); assertPublic(completed);
    const verificationDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const completedPrivate = verificationDb.prepare('SELECT private_path,srt_path FROM transcript_files WHERE id=?').get(completed.files[0].id); assert.equal(completedPrivate.private_path, '', 'successful transcription removes the materialized full-media copy'); assert(fs.existsSync(completedPrivate.srt_path), 'SRT remains after media cleanup'); verificationDb.close();
    const detail = await request('transcript.file.get.v1', { fileId: completed.files[0].id }); assert.equal(detail.segments.length, 2); assert.equal(detail.segments[0].text, '第一条字幕'); assertPublic(detail);
    const searched = await request('transcript.search.v1', { query: '搜索' }); assert.equal(searched.results.length, 1); assert.equal(searched.results[0].fileId, completed.files[0].id); assertPublic(searched);
    const longStart = await startSelectedSources([sources.long]); const longDone = await request('transcript.operation.run.v1', { operationId: longStart.operationId }); const deepSearch = await request('transcript.search.v1', { query: '深页搜索' }); assert.equal(deepSearch.results[0].operationId, longDone.id); assert.equal(deepSearch.results[0].seq, 320); const targeted = await request('transcript.file.get.v1', { fileId: longDone.files[0].id, targetSeq: 320, pageSize: 200 }); assert.equal(targeted.page.offset, 200); assert(targeted.segments.some(item => item.seq === 320), 'a search target beyond segment 200 is returned in its bounded window'); assert.equal(targeted.segments.length, 200);
    const searchSeen = new Set(); let searchCursor = ''; let searchPages = 0; do { const page = await request('transcript.search.v1', { query: '字幕', cursor: searchCursor, limit: 50 }); assert(page.results.length <= 50); for (const item of page.results) { const key = `${item.operationId}:${item.fileId}:${item.seq}`; assert(!searchSeen.has(key), 'stable search cursor never repeats a result'); searchSeen.add(key); } searchCursor = page.page.nextCursor || ''; searchPages += 1; } while (searchCursor && searchPages < 20); assert(searchSeen.size > 200, 'search matches beyond the former 200-result ceiling remain reachable'); assert.equal(searchCursor, '', 'search cursor reaches the final page');
    const allFirst = await request('transcript.operation.transcript.page.v1', { operationId: longDone.id, pageSize: 120 }); assert.equal(allFirst.items.length, 120); assert(allFirst.page.nextCursor && !/^\d+$/.test(allFirst.page.nextCursor), 'all-transcript cursor is an opaque stable keyset'); const allSecond = await request('transcript.operation.transcript.page.v1', { operationId: longDone.id, cursor: allFirst.page.nextCursor, pageSize: 120 }); assert.equal(allSecond.items[0].seq, 121); assert(allSecond.page.previousCursor); const allBack = await request('transcript.operation.transcript.page.v1', { operationId: longDone.id, cursor: allSecond.page.previousCursor, pageSize: 120 }); assert.deepEqual(allBack.items.map(item => item.seq), allFirst.items.map(item => item.seq), 'keyset previous cursor returns the exact prior page without OFFSET drift');
    const published = await request('transcript.output.publish.v1', { fileId: completed.files[0].id }); assert.equal(published.published, true); assert.equal(published.output.controlled, false); assert.match(published.output.sha256, /^[a-f0-9]{64}$/); assert(published.output.size > 0); assert.match(published.message, /媒体旁/); const firstCommit = capabilityCalls.findLast(call => call.method === 'project.output.v7' && call.payload.action === 'commit'); assert.equal(firstCommit.payload.idempotencyKey.length, 68); assert.match(firstCommit.payload.idempotencyKey, /^srt-[a-f0-9]{64}$/); assertPublic(published); assert((await request('transcript.output.open.v1', { fileId: completed.files[0].id })).opened);
    const stageCalls = capabilityCalls.filter(call => call.method === 'project.output.v7' && call.payload.action === 'stage').length; const repeated = await request('transcript.output.publish.v1', { fileId: completed.files[0].id }); assert.equal(repeated.idempotent, true); assert.equal(capabilityCalls.filter(call => call.method === 'project.output.v7' && call.payload.action === 'stage').length, stageCalls, 'same-content retry does not leak another stage');
    const editDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const srtPath = editDb.prepare('SELECT srt_path FROM transcript_files WHERE id=?').get(completed.files[0].id).srt_path; fs.appendFileSync(srtPath, '\nedited'); editDb.close(); const replaced = await request('transcript.output.publish.v1', { fileId: completed.files[0].id }); assert.notEqual(replaced.output.sha256, published.output.sha256, 'changed content performs a controlled digest-bound replacement');

    const beforeBatchProcesses = fs.existsSync(processLog) ? fs.readFileSync(processLog, 'utf8').trim().split(/\r?\n/).filter(Boolean).length : 0;
    const beforeMaterialize = materializeCount; const partialStart = await startSelectedSources([sources.good, sources.bad, sources.good]); tokens.clear(); const partial = await request('transcript.operation.run.v1', { operationId: partialStart.operationId }); assert.equal(materializeCount - beforeMaterialize, 3); assert.equal(partial.state, 'partial_failure'); assert.equal(partial.succeeded, 2); assert.equal(partial.failed, 1); assert.equal(partial.files.length, 3); assert(taskState.get(`project-test:${partial.id}`).actions.at(-1) === 'complete', 'partial failure reaches task completion only after every file'); const afterBatchProcesses = fs.readFileSync(processLog, 'utf8').trim().split(/\r?\n/).filter(Boolean).length; assert.equal(afterBatchProcesses - beforeBatchProcesses, 1, 'one operation reuses one persistent algorithm process/model across all files'); assertPublic(partial);
    const partialDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const partialRows = partialDb.prepare('SELECT state,private_path FROM transcript_files WHERE operation_id=? ORDER BY ordinal').all(partial.id); assert(partialRows.every(row => row.private_path === ''), 'project inputs are rematerialized on retry and never retained'); partialDb.close();

    const bulkSuccessStart = await startSelectedSources([sources.good, sources.good]); const bulkSuccessDone = await request('transcript.operation.run.v1', { operationId: bulkSuccessStart.operationId }); const bulkSuccess = await request('transcript.output.publish-all.v1', { operationId: bulkSuccessDone.id }); assert.deepEqual({ total: bulkSuccess.total, published: bulkSuccess.published, idempotent: bulkSuccess.idempotent, failed: bulkSuccess.failed, cancelled: bulkSuccess.cancelled }, { total: 2, published: 2, idempotent: 0, failed: 0, cancelled: false }); assert(taskState.get(`project-test:${bulkSuccess.taskId}`).actions.includes('start')); assert.equal(taskState.get(`project-test:${bulkSuccess.taskId}`).actions.at(-1), 'complete');
    const bulkIdempotent = await request('transcript.output.publish-all.v1', { operationId: bulkSuccessDone.id }); assert.equal(bulkIdempotent.published, 0); assert.equal(bulkIdempotent.idempotent, 2); assert.equal(bulkIdempotent.failed, 0);
    const bulkConflictStart = await startSelectedSources([sources.good, sources.good]); const bulkConflictDone = await request('transcript.operation.run.v1', { operationId: bulkConflictStart.operationId }); const foreignPath = `project-test:${bulkConflictDone.files[0].relativeName.replace(/\.[^.]+$/, '.srt')}`; committedPaths.set(foreignPath, { commitId: crypto.randomUUID(), artifactId: crypto.randomUUID(), sha256: 'f'.repeat(64) }); const bulkConflict = await request('transcript.output.publish-all.v1', { operationId: bulkConflictDone.id }); assert.equal(bulkConflict.total, 2); assert.equal(bulkConflict.published, 1, 'one conflict does not prevent a later file publication'); assert.equal(bulkConflict.failed, 1); assert.equal(bulkConflict.failures.length, 1); assert.match(bulkConflict.failures[0].error, /output conflict/); assert(!JSON.stringify(bulkConflict).includes(sandbox));
    const bulkCancelStart = await startSelectedSources([sources.good, sources.good]); const bulkCancelDone = await request('transcript.operation.run.v1', { operationId: bulkCancelStart.operationId }); cancelNextPublishReport = true; const bulkCancelled = await request('transcript.output.publish-all.v1', { operationId: bulkCancelDone.id }); assert.equal(bulkCancelled.cancelled, true); assert.equal(bulkCancelled.published, 1); assert.equal(taskState.get(`project-test:${bulkCancelled.taskId}`).actions.at(-1), 'cancel');

    const sensitiveBefore = capabilityCalls.filter(call => call.projectId === 'project-other' && ['tasks.v7', 'project.output.v7', 'dialogs.v7'].includes(call.method)).length;
    assert.deepEqual((await request('transcript.operation.list.v1', {}, 'project-other')).operations, []); assert.deepEqual((await request('transcript.search.v1', { query: '搜索' }, 'project-other')).results, []);
    for (const [method, payload] of [['transcript.operation.get.v1', { operationId: completed.id }], ['transcript.operation.run.v1', { operationId: completed.id }], ['transcript.operation.cancel.v1', { operationId: completed.id }], ['transcript.operation.resume.v1', { operationId: completed.id }], ['transcript.file.get.v1', { fileId: completed.files[0].id }], ['transcript.output.publish.v1', { fileId: completed.files[0].id }], ['transcript.output.publish-all.v1', { operationId: completed.id }], ['transcript.output.open.v1', { fileId: completed.files[0].id }]]) await assert.rejects(request(method, payload, 'project-other'), /找不到|尚未生成|请先发布/);
    assert.equal(capabilityCalls.filter(call => call.projectId === 'project-other' && ['tasks.v7', 'project.output.v7', 'dialogs.v7'].includes(call.method)).length, sensitiveBefore, 'cross-project IDs never reach tasks, output, or media-reference capabilities');

    const conflictStart = await startSelectedSources([sources.good]); const conflictDone = await request('transcript.operation.run.v1', { operationId: conflictStart.operationId }); const conflictPath = `project-test:${conflictDone.files[0].relativeName.replace(/\.[^.]+$/, '.srt')}`; committedPaths.set(conflictPath, { commitId: crypto.randomUUID(), artifactId: crypto.randomUUID(), sha256: 'a'.repeat(64) }); await assert.rejects(request('transcript.output.publish.v1', { fileId: conflictDone.files[0].id }), /output conflict/, 'foreign pre-existing output remains a conflict');

    for (const action of ['resume', 'status', 'report', 'complete']) {
      const retryStart = await startSelectedSources([sources.good]); failTaskAction.set(`project-test:${action}`, true); await assert.rejects(request('transcript.operation.run.v1', { operationId: retryStart.operationId }), /simulated tasks/); const retry = await request('transcript.operation.run.v1', { operationId: retryStart.operationId }); assert.notEqual(retry.alreadyRunning, true, `${action} failure must not poison runningOperations`); assert.equal(retry.state, 'completed');
    }
    const failRetryStart = await startSelectedSources([sources.bad]); failTaskAction.set('project-test:fail', true); await assert.rejects(request('transcript.operation.run.v1', { operationId: failRetryStart.operationId }), /simulated tasks fail/); const failRetry = await request('transcript.operation.run.v1', { operationId: failRetryStart.operationId }); assert.notEqual(failRetry.alreadyRunning, true); assert.equal(failRetry.state, 'failed');

    const projectStart = await request('transcript.project.start.v1', {}, 'project-test', ['project-bad.mp4']); const beforeProjectMaterialize = materializeCount; const projectFailed = await request('transcript.operation.run.v1', { operationId: projectStart.operationId }); assert.equal(projectFailed.state, 'failed'); assert.equal(materializeCount, beforeProjectMaterialize + 1); const projectDb = new DatabaseSync(path.join(storageRoot, 'storage.sqlite3')); const projectRow = projectDb.prepare('SELECT private_path,media_ref_json FROM transcript_files WHERE operation_id=?').get(projectStart.operationId); assert.equal(projectRow.private_path, '', 'failed project media copy is deleted'); assert.match(projectRow.media_ref_json, /project-bad\.mp4/, 'project media reference is retained for reauthorization'); projectDb.close(); projectMedia.set('project-bad.mp4', sources.good); await request('transcript.operation.resume.v1', { operationId: projectStart.operationId }); const projectRecovered = await request('transcript.operation.run.v1', { operationId: projectStart.operationId }); assert.equal(projectRecovered.state, 'completed'); assert.equal(materializeCount, beforeProjectMaterialize + 2, 'project media retry obtains a fresh one-time token');

    const cleanupRoot = path.join(sandbox, 'cleanup-storage'); const cleanupInputs = path.join(cleanupRoot, 'inputs', 'one'); const cleanupSubtitles = path.join(cleanupRoot, 'subtitles'); fs.mkdirSync(cleanupInputs, { recursive: true }); fs.mkdirSync(cleanupSubtitles, { recursive: true }); const cleanupDb = path.join(cleanupRoot, 'storage.sqlite3'); const cleanupMedia = path.join(cleanupInputs, 'media.mp4'); const cleanupSrt = path.join(cleanupSubtitles, 'keep.srt'); const outside = path.join(sandbox, 'outside.mp4'); fs.writeFileSync(cleanupDb, 'db'); fs.writeFileSync(cleanupMedia, 'media'); fs.writeFileSync(cleanupSrt, 'srt'); fs.writeFileSync(outside, 'outside'); const { removePrivateInput } = require('../service.cjs'); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, cleanupSrt), false); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, cleanupDb), false); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, outside), false); assert(fs.existsSync(cleanupSrt) && fs.existsSync(cleanupDb) && fs.existsSync(outside)); let linked = ''; try { linked = path.join(cleanupRoot, 'inputs', 'linked.mp4'); fs.symlinkSync(outside, linked, 'file'); assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, linked), false); assert(fs.existsSync(outside)); } catch (error) { if (!['EPERM', 'EACCES'].includes(error.code)) throw error; } assert.equal(await removePrivateInput({ dataPath: cleanupRoot, databasePath: cleanupDb }, cleanupMedia), true); assert(!fs.existsSync(cleanupMedia));

    const cancelStart = await startSelectedSources([sources.slow]); const running = request('transcript.operation.run.v1', { operationId: cancelStart.operationId }); await new Promise(resolve => setTimeout(resolve, 180)); const cancelled = await request('transcript.operation.cancel.v1', { operationId: cancelStart.operationId }); assert.equal(cancelled.state, 'cancelled'); const cancelledRun = await running; assert.equal(cancelledRun.state, 'cancelled'); assert(taskState.get(`project-test:${cancelStart.operationId}`).actions.includes('cancel')); assertPublic(cancelledRun);
    const resumed = await request('transcript.operation.resume.v1', { operationId: cancelStart.operationId }); assert.equal(resumed.accepted, true); assert.equal(resumed.operationId, cancelStart.operationId); const resumedRun = await request('transcript.operation.run.v1', { operationId: cancelStart.operationId }); assert.equal(resumedRun.state, 'completed'); assert.equal(resumedRun.succeeded, 1);
    console.log('video-transcription service selection resolution, project isolation, cleanup, persistent engine, failure recovery, cancel, search, and strict publish tests passed');
  } finally { child.kill(); fs.rmSync(sandbox, { recursive: true, force: true }); if (createdTestModel) fs.rmSync(testModelRoot, { recursive: true, force: true }); }
})().catch(error => { console.error(error); child.kill(); fs.rmSync(sandbox, { recursive: true, force: true }); if (createdTestModel) fs.rmSync(testModelRoot, { recursive: true, force: true }); process.exitCode = 1; });
