/* eslint-disable react-refresh/only-export-components -- packaged renderer entry defines and mounts its private root components */
import { StrictMode, useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createPortal } from 'react-dom';
import { RotateCcw, Settings, UsersRound, Wrench, X } from 'lucide-react';
import { TeamRetouchManager } from './legacy/TeamRetouchManager';
import { PersonIdentityManager } from './legacy/PersonIdentityManager';
import { LegacyDialogProvider } from './legacy/legacy-dialog';
import { useAppDialog } from './legacy/legacy-dialog-context';
import type { TeamRetouchStep } from './legacy/TeamRetouchSteps';
import { rpc, type ComponentContext } from './sdk';
import { legacyApi } from './legacy/legacy-api';
import './legacy-style.css';

type Json = Record<string, any>;
type TeamSettings = { useGpu: boolean; oversizeCropMode: 'face-centered' | 'expand' };
const assertSuccess = (value: Json, fallback: string) => { if (value?.success === false) throw new Error(value.error || fallback); return value; };

const TeamSettingsDialog = ({ value, update, close, notice }: { value: TeamSettings; update: (value: TeamSettings) => void; close: () => void; notice: (message: string) => void }) => {
  const appDialog = useAppDialog();
  const [busy, setBusy] = useState(''); const [environment, setEnvironment] = useState<Json>();
  const run = async (label: string, action: () => Promise<void>) => { if (busy) return; setBusy(label); try { await action(); notice(`${label}完成`); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } finally { setBusy(''); } };
  const save = (next: TeamSettings) => { update(next); void run('保存团片协作设置', async () => { assertSuccess(await rpc<Json>('component.settings.update.v1', next), '保存设置失败'); }); };
  return createPortal(<div className="fixed inset-0 z-[850] flex items-center justify-center bg-slate-950/55 p-4"><section role="dialog" aria-modal="true" aria-label="团片协作设置" className="flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl"><header className="flex min-h-14 items-center gap-3 border-b border-slate-200 px-5"><span className="rounded-lg bg-blue-50 p-2 text-blue-600"><Settings size={18}/></span><div><h2 className="text-sm font-bold text-slate-900">团片协作设置</h2><p className="mt-0.5 text-[11px] text-slate-500">处理偏好与团片协作专属识别环境</p></div><button className="ml-auto rounded-md p-2 text-slate-500 hover:bg-slate-100" onClick={close} aria-label="关闭设置"><X size={18}/></button></header><div className="min-h-0 flex-1 space-y-5 overflow-y-auto bg-slate-50 p-5">
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><h3 className="border-b border-slate-200 px-4 py-3 text-xs font-bold text-slate-700">处理偏好</h3><div className="flex items-center justify-between gap-5 px-4 py-3.5"><div><h4 className="text-sm font-bold text-slate-800">优先使用 GPU</h4><p className="mt-1 text-xs text-slate-500">显卡不支持或运行失败时，基础人物检测会自动回退 CPU。</p></div><button role="switch" aria-checked={value.useGpu} className={`relative h-6 w-11 rounded-full ${value.useGpu ? 'bg-blue-600' : 'bg-slate-300'}`} onClick={() => save({ ...value, useGpu: !value.useGpu })}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value.useGpu ? 'left-6' : 'left-1'}`}/></button></div><div className="flex items-center justify-between gap-5 border-t border-slate-100 px-4 py-3.5"><div><h4 className="text-sm font-bold text-slate-800">裁剪方式</h4><p className="mt-1 text-xs text-slate-500">人物超过 4000 像素时，可限制尺寸或保留完整人物；后者可能超出手机修图软件限制。</p></div><select className="form-input max-w-sm" value={value.oversizeCropMode} onChange={event => save({ ...value, oversizeCropMode: event.target.value as TeamSettings['oversizeCropMode'] })}><option value="face-centered">保持 4000 像素</option><option value="expand">扩大裁剪，保留完整人物</option></select></div></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><h3 className="border-b border-slate-200 px-4 py-3 text-xs font-bold text-slate-700">识别引擎</h3><div className="flex items-start justify-between gap-5 px-4 py-3.5"><div><h4 className="text-sm font-bold text-slate-800">基础人物检测</h4><p className="mt-1 text-xs text-slate-500">提供基础人物检测、裁图和分割。</p></div><p className="text-xs font-bold text-emerald-600">可用</p></div><div className="flex items-start justify-between gap-5 border-t border-slate-100 px-4 py-3.5"><div><h4 className="text-sm font-bold text-slate-800">人物身份识别</h4><p className="mt-1 text-xs text-slate-500">用于跨照片识别同一人物。支持 CPU；可用显卡会自动加速。</p></div><p className="text-xs font-bold text-emerald-600">可用</p></div></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><h3 className="border-b border-slate-200 px-4 py-3 text-xs font-bold text-slate-700">人物检测增强版</h3><div className="flex items-start justify-between gap-5 px-4 py-3.5"><div><h4 className="text-sm font-bold text-slate-800">PairDETR + SAM 2.1</h4><p className="mt-1 text-xs text-slate-500">改善多人、遮挡和精细分割效果。</p>{environment && <pre className="mt-3 max-w-xl whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-[11px] text-slate-600">{environment.message || environment.error || JSON.stringify(environment, null, 2)}</pre>}</div><div className="flex flex-wrap justify-end gap-2"><button className="dialog-secondary inline-flex items-center gap-2" onClick={() => void run('检查安装条件', async () => setEnvironment(await rpc<Json>('component.advanced.preflight.v1')))} disabled={Boolean(busy)}><RotateCcw size={14}/>检查</button><button className="dialog-primary inline-flex items-center gap-2" onClick={() => void run('安装或修复增强版', async () => { assertSuccess(await rpc<Json>('component.advanced.install.v1', { repair: true }), '安装失败'); setEnvironment(await rpc<Json>('component.advanced.preflight.v1')); })} disabled={Boolean(busy)}><Wrench size={14}/>安装 / 修复</button><button className="rounded-md border border-red-200 bg-white px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-50" onClick={() => void run('卸载增强版', async () => { if (!await appDialog.confirm({ title: '卸载人物检测增强版吗？', message: '将删除 PairDETR、SAM 2.1 和独立运行环境；基础检测和身份识别不受影响。', confirmLabel: '卸载增强版', tone: 'danger' })) return; assertSuccess(await rpc<Json>('component.advanced.uninstall.v1'), '卸载失败'); setEnvironment(undefined); })} disabled={Boolean(busy)}>卸载</button></div></div><div className="border-t border-slate-100 px-4 py-3.5"><h4 className="text-sm font-bold text-slate-800">安装条件</h4><p className="mt-1 text-xs leading-5 text-slate-500">Windows x64、WSL 2、支持 WSL CUDA 的 NVIDIA 显卡与驱动，以及至少 35 GB 可用空间。建议至少 8 GB 显存和 16 GB 系统内存。</p></div></section>
  </div></section></div>, document.body);
};

const App = () => {
  const [context, setContext] = useState<ComponentContext>(); const [entries, setEntries] = useState<Json[]>([]); const [step, setStep] = useState<TeamRetouchStep>('detect'); const [settings, setSettings] = useState<TeamSettings>({ useGpu: true, oversizeCropMode: 'face-centered' }); const [settingsOpen, setSettingsOpen] = useState(false); const [notice, setNotice] = useState('');
  const loadEntries = useCallback(async () => { const pages: Json[] = []; let cursor = ''; do { const page = assertSuccess(await rpc<Json>('project.files.list.v1', cursor ? { cursor } : {}), '无法读取项目图片'); pages.push(page); cursor = page.hasMore ? String(page.cursor || '') : ''; } while (cursor && pages.length < 100); const next = pages.flatMap(page => page.entries || page.files || []).filter((entry: Json) => entry.kind === 'image' || /\.(jpe?g|png|tiff?|heic|webp|dng|cr[23]|nef|arw|raf)$/i.test(entry.name || entry.relativePath || '')); legacyApi.setProjectEntries(next); setEntries(next); }, []);
  useEffect(() => { let mounted = true; void Promise.all([window.photoFlowComponent.getContext(), rpc<Json>('component.settings.get.v1'), loadEntries()]).then(([nextContext, saved]) => { if (!mounted) return; setContext(nextContext); if (saved.success !== false && saved.settings) setSettings(saved.settings as TeamSettings); }).catch(error => setNotice(error instanceof Error ? error.message : String(error))); return () => { mounted = false; }; }, [loadEntries]);
  const project = { id: context?.projectId || '', name: context?.projectName || '', status: context?.projectStatus || '', path: '' };
  const common = { workspacePath: context?.projectId || '', project, cacheConfig: { directory: '', maxSizeGB: 0 }, activeStep: step, onStepChange: setStep, onClose: () => undefined, onOpenSettings: () => setSettingsOpen(true), onNotice: setNotice, onProjectChanged: loadEntries };
  return <LegacyDialogProvider><div className="legacy-root">{step === 'workflow' ? <PersonIdentityManager {...common} onClose={common.onOpenSettings} activeStep="workflow"/> : <TeamRetouchManager {...common} entries={entries as any} onEntriesChange={value => setEntries(value)} />}{notice && <div className="fixed bottom-5 left-1/2 z-[820] flex max-w-2xl -translate-x-1/2 items-center gap-3 rounded-lg bg-slate-900 px-4 py-3 text-sm font-bold text-white shadow-xl"><UsersRound size={16}/><span>{notice}</span><button className="ml-2 text-slate-300" onClick={() => setNotice('')}>×</button></div>}{settingsOpen && <TeamSettingsDialog value={settings} update={setSettings} close={() => setSettingsOpen(false)} notice={setNotice}/>}</div></LegacyDialogProvider>;
};
createRoot(document.getElementById('app')!).render(<StrictMode><App/></StrictMode>);
