export type VideoActionId = 'video.playPause' | 'video.seekBackward' | 'video.seekForward' | 'video.frameBackward' | 'video.frameForward' | 'video.volumeUp' | 'video.volumeDown' | 'video.mute' | 'video.speedUp' | 'video.speedDown' | 'video.resetSpeed' | 'video.fullscreen' | 'video.exitFullscreen' | 'video.capture' | 'video.subtitles' | 'video.info' | 'media.previous' | 'media.next';
export type VideoShortcutInput = { key: string; code: string; ctrl: boolean; alt: boolean; shift: boolean; meta: boolean; repeat: boolean };
export type VideoShortcutBindings = Record<VideoActionId, string[]>;
export const VIDEO_ACTIONS: ReadonlyArray<{ id: VideoActionId; label: string; scope: 'video' | 'media'; defaults: string[] }> = [
  {id:'video.playPause',label:'播放 / 暂停',scope:'video',defaults:['Space','KeyK']},{id:'video.seekBackward',label:'快退 5 秒',scope:'video',defaults:['ArrowLeft']},{id:'video.seekForward',label:'快进 5 秒',scope:'video',defaults:['ArrowRight']},
  {id:'video.frameBackward',label:'后退一帧',scope:'video',defaults:['Comma']},{id:'video.frameForward',label:'前进一帧',scope:'video',defaults:['Period']},{id:'video.volumeUp',label:'增大音量',scope:'video',defaults:['ArrowUp']},{id:'video.volumeDown',label:'减小音量',scope:'video',defaults:['ArrowDown']},{id:'video.mute',label:'静音',scope:'video',defaults:['KeyM']},
  {id:'video.speedUp',label:'提高速度',scope:'video',defaults:['BracketRight']},{id:'video.speedDown',label:'降低速度',scope:'video',defaults:['BracketLeft']},{id:'video.resetSpeed',label:'恢复 1×',scope:'video',defaults:['Backslash']},{id:'video.fullscreen',label:'进入 / 退出全屏',scope:'video',defaults:['KeyF']},{id:'video.exitFullscreen',label:'退出全屏',scope:'video',defaults:['Escape']},
  {id:'video.capture',label:'截取当前帧',scope:'video',defaults:['Ctrl+Shift+KeyS']},{id:'video.subtitles',label:'字幕菜单',scope:'video',defaults:['KeyC']},{id:'video.info',label:'播放信息',scope:'video',defaults:['KeyI']},{id:'media.previous',label:'上一个视频',scope:'media',defaults:['PageUp']},{id:'media.next',label:'下一个视频',scope:'media',defaults:['PageDown']},
];
const ACTION_IDS = new Set(VIDEO_ACTIONS.map(item=>item.id));
const RESERVED = new Set(['Alt+F4','Ctrl+Alt+Delete','Meta+KeyL','Meta+KeyQ','Ctrl+Shift+Escape']);
const normalizeKeyToken=(value:string)=>value===' '?'Space':value.length===1?`Key${value.toUpperCase()}`:value;
const canonicalizeChord=(value:string)=>{const parts=value.split('+').map(item=>item.trim()).filter(Boolean);if(!parts.length)return'';parts[parts.length-1]=normalizeKeyToken(parts[parts.length-1]);return parts.join('+');};
export const shortcutChord=(input:VideoShortcutInput)=>[input.ctrl?'Ctrl':'',input.alt?'Alt':'',input.shift?'Shift':'',input.meta?'Meta':'',normalizeKeyToken(input.code||input.key)].filter(Boolean).join('+');
export const isReservedVideoShortcut=(chord:string)=>RESERVED.has(chord);
export const defaultVideoShortcutBindings=():VideoShortcutBindings=>Object.fromEntries(VIDEO_ACTIONS.map(item=>[item.id,[...item.defaults]])) as VideoShortcutBindings;
export const normalizeVideoShortcutBindings=(value:unknown):VideoShortcutBindings=>{const defaults=defaultVideoShortcutBindings(),raw=value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};for(const action of VIDEO_ACTIONS){const entries=Array.isArray(raw[action.id])?raw[action.id] as unknown[]:defaults[action.id];const normalized=[...new Set(entries.map(String).map(canonicalizeChord).filter(item=>item&&!isReservedVideoShortcut(item)))].slice(0,4);defaults[action.id]=normalized.length?normalized:[...action.defaults];}return defaults;};
export const videoShortcutConflicts=(bindings:VideoShortcutBindings)=>{const owners=new Map<string,VideoActionId[]>();for(const action of VIDEO_ACTIONS)for(const chord of bindings[action.id])owners.set(chord,[...(owners.get(chord)||[]),action.id]);return [...owners].filter(([,actions])=>actions.length>1).map(([chord,actions])=>({chord,actions}));};
export const resolveVideoShortcut=(input:VideoShortcutInput,bindings:VideoShortcutBindings,{editable=false,scope='video'}:{editable?:boolean;scope?:'video'|'media'}={}):VideoActionId|null=>{const chord=shortcutChord(input);if(isReservedVideoShortcut(chord)||(editable&&chord!=='Escape'))return null;for(const action of VIDEO_ACTIONS)if((action.scope==='video'||scope==='media')&&bindings[action.id].includes(chord))return action.id;return null;};
export const bindingsForArrowMode=(bindings:VideoShortcutBindings,mode:'seek'|'navigate'):VideoShortcutBindings=>{const result=normalizeVideoShortcutBindings(bindings);if(mode==='navigate'){result['video.seekBackward']=result['video.seekBackward'].filter(item=>item!=='ArrowLeft');result['video.seekForward']=result['video.seekForward'].filter(item=>item!=='ArrowRight');result['media.previous']=[...new Set([...result['media.previous'],'ArrowLeft'])];result['media.next']=[...new Set([...result['media.next'],'ArrowRight'])];}return result;};
export const exportVideoShortcuts=(bindings:VideoShortcutBindings)=>JSON.stringify({schemaVersion:1,kind:'photoflow-video-shortcuts',bindings:normalizeVideoShortcutBindings(bindings)},null,2);
export const importVideoShortcuts=(text:string)=>{const value=JSON.parse(text);if(!value||value.schemaVersion!==1||value.kind!=='photoflow-video-shortcuts'||Object.keys(value).some(key=>!['schemaVersion','kind','bindings'].includes(key))||!value.bindings||Object.keys(value.bindings).some(key=>!ACTION_IDS.has(key as VideoActionId)))throw new Error('快捷键配置格式无效');const bindings=normalizeVideoShortcutBindings(value.bindings);const conflicts=videoShortcutConflicts(bindings);if(conflicts.length)throw new Error(`快捷键冲突：${conflicts[0].chord}`);return bindings;};
export const shortcutInputFromKeyboardEvent=(event:Pick<KeyboardEvent,'key'|'code'|'ctrlKey'|'altKey'|'shiftKey'|'metaKey'|'repeat'>):VideoShortcutInput=>({key:event.key,code:event.code||event.key,ctrl:event.ctrlKey,alt:event.altKey,shift:event.shiftKey,meta:event.metaKey,repeat:event.repeat});
