name: Build & Release

on:
  push:
    tags:
      - "v*" # 只有推送到 v1.0.0, v1.0.1 这种标签时才运行

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # 如果你需要同时发 Mac, Windows, Linux 版，就全写上macos-latest, ubuntu-latest
        # 如果只要 Windows，就只写 windows-latest
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # 根据你的项目要求选择版本

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish
        # 这里是核心：使用 electron-builder 打包并发布
        # GH_TOKEN 是 GitHub 自动提供的，用于上传文件
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: npm run electron-builder -- --publish always